### ISSUE TITLE
Shareware version of Aliens of Gold doesn't work

### ISSUE THREAD

**Issue by ibara** [bibendovsky/bstone#111]
When using the latest git HEAD of bstone, the shareware version of the game does not load.

Error message that pops up:
CRITICAL: Mismatch GFX header offset count

The full versions of Aliens of Gold and Planet Strike (from GOG.com) work fine.

Discovered when testing the OpenBSD package of bstone. Relevant entry from our mailing lists here:
https://marc.info/?l=openbsd-ports&m=154586787920691&w=2

**Comment by bibendovsky** [comment]
The error was before ada1050a2ec57ac6d147e85cb0c399de7854d0fa in branch fix/revise_code.

**Comment by ibara** [comment]
Yup, looks like we made our package before you made that commit. Updated our code, thanks.
