### ISSUE TITLE
v1.1.10 ignores --profile_dir

### ISSUE THREAD

**Issue by DanKorell** [bibendovsky/bstone#119]
I noticed that v1.1.10 was recently released so I updated my installation. I use --profile_dir to specify my desired location for the settings and save games, but I noticed that v1.1.10 ignores this and still saves within the C:\Users\username\AppData\Roaming\bibendovsky\bstone folder instead. But if I revert back to v1.1.9 then it starts using my own specified folder again.

**Comment by bibendovsky** [comment]
Fixed in #121. Merged into develop. Binaries will be later.

**Comment by bibendovsky** [comment]
Done. Please check release v1.1.11.

**Comment by DanKorell** [comment]
Yep, that's working fine now. Thanks!
