### ISSUE TITLE
No Real Wide and Ultrawide Screen

### ISSUE THREAD

**Issue by TP555** [bibendovsky/bstone#131]
Hi

Good Work so far :D

But no Real WideScreen or UltraWide , is like 4:3

You plan in Future real 16:9 and 21:9 ?

Or a option for Change the FOV , the Screen is filled too with 2560x1080 , so can work a Fov Option .

Some ECWolf DevBuilds supports 16:9 and 21:9 !

Here is an Video ECWolf in 21:9 , this have a bit Fov from ECWolf for both Aspects

https://www.youtube.com/watch?v=1J9rXjZV5QA

TP555

**Comment by bibendovsky** [comment]
Hello. Something like this?

![bstone_diff_flen](https://user-images.githubusercontent.com/1597301/51108643-82312600-17fb-11e9-9b50-277f3bb22d92.png)

The upper part with default focal length. The lower one with minimum focal length.

**Comment by TP555** [comment]
Re

Which Resolution is that  ?

The lower looks fine for 21:9 , but this res looks like Multi Monitor Res !

Best Fov for 21:9 is 115-120

TP555

**Comment by bibendovsky** [comment]
> Which Resolution is that
960x240

**Comment by TP555** [comment]
Re

Why so an low Resolution ? ,
Native 21:9 have 2560x1080 or 3440x1440  :dagger:

But you can add a Fov Option as command  ?
Or Try a Native 16:9 , or 21:9 , even what is possible ?

But the most 16:9 or Most for 21:9 can just force with Fov Hacks , but Soldier of Fortune 1 CE with Sofplus have Native 21:9 , you can compare the Fov H and V in compare to the Original 4:3 Version  !

https://www.youtube.com/watch?v=d0CScFhwZKc&t=6s

But when you watch my Another Videos , then you see , the most works with Fov Hacks , or set an Fov Automatlicly for each Res.

TP555

**Comment by TP555** [comment]
Re

And any new News , about Native Widescreen /Ultrawide , or a Fov Slider to Force any Widescreen Aspect ?

TP555

**Comment by bibendovsky** [comment]
> And any new News , about Native Widescreen /Ultrawide , or a Fov Slider to Force any Widescreen Aspect ?

I'm working on 3D rendering now.
FOV support for vanilla rendering will be added after it.

**Comment by TP555** [comment]
Re

ah , you mean , Texture Filtering  ?

TP555

**Comment by bibendovsky** [comment]
> ah , you mean , Texture Filtering ?

Geometry, objects, etc.

**Comment by bibendovsky** [comment]
Fixed in v1.2.0.
