### ISSUE TITLE
cmake exits with: extension ".c" not supported

### ISSUE THREAD

**Issue by bymoz089** [bibendovsky/bstone#132]
Tried to compile on debian stretch.
cmake exits with error: 

> Unknown extension ".c" for file

See here for similar problem and fix: http://www.grokit.ca/cnt/CMakeProblemsSolutions/

I fixed this by adding 
`ENABLE_LANGUAGE(C)`
to file `src/CMakeLists.txt`

**Comment by bibendovsky** [comment]
Seems it is happening because of script TestBigEndian, which tries to compile test program(s) written for C.

**Comment by bibendovsky** [comment]
Please test branch "fix/#132_endian".

**Comment by bibendovsky** [comment]
CMake works fine for mentioned above branch.
Tested on Debian 9.6 x64.

**Comment by bibendovsky** [comment]
Merged into develop.
