### ISSUE TITLE
Error running CMake in Ubuntu

### ISSUE THREAD

**Issue by JPLeBreton** [bibendovsky/bstone#15]
Trying to compile on Ubuntu 14.10 64-bit, I get this error running cmake:

-- Could NOT find Threads (missing:  Threads_FOUND) 
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find SDL: Found unsuitable version "1.2.15", but required is at
  least "2" (found
  /usr/lib/x86_64-linux-gnu/libSDLmain.a;/usr/lib/x86_64-linux-gnu/libSDL.so)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:313 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindSDL.cmake:176 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:4 (find_package)

I definitely have libsdl2-2.0-0 + -dev installed, etc.

**Comment by bibendovsky** [comment]
You have to specify paths to headers and libraries explicitly. Also to avoid farther issues with installed SDL2 I recommend you to download a latest one (2.0.3) and build it manually.

Here is an example of my configuration:
![bstone_cmake_gui_ubuntu_x64_4bit](https://cloud.githubusercontent.com/assets/1597301/6408224/ab5a68da-be58-11e4-86ab-11cac60e2d2d.png)

P.S. To set CMAKE_BUILD_TYPE variable click Advanced.

**Comment by Manuel-K** [comment]
This should be obsolete by the changes from commit df34dfa7fd6d3c1367d2b2788e68a2e411121a62.
