### ISSUE TITLE
Hi i'm trying to get it to compile on the raspberry pi

### ISSUE THREAD

**Issue by HereticOne** [bibendovsky/bstone#150]
I have no idea how to do so.
it's basically linux so should be possible.
Please help

**Comment by bibendovsky** [comment]
Hello.
I'll try to describe a generic build procedure for Linux.

1. Install minimum required software:
- CMake 3.1.3 or higher.
- C++14 compatible compiler (GCC or clang).
- SDL library v2.0.4 or higher.

2. Download source code (https://github.com/bibendovsky/bstone/releases) and extract it somewhere (for example, "~/bstone").

3. Change the current directory to "~/bstone/build".

4. Generate Makefile:
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/bstone/build/install

5. Build and install:
make install

6. On success you will find executable in the directory "~/bstone/build/install".
