### ISSUE TITLE
Where should SDL2_DIR point to exactly?

### ISSUE THREAD

**Issue by Uberwire** [bibendovsky/bstone#152]
I'm using CMake on Windows 7 and have downloaded SDL Source Code and Development Libraries, but do not know where to point the `SDL2_DIR` variable to. If I point to the root of the SDL directories where the two configuration files are then I get` SDL2_DIR-NOTFOUND` and an error that goes like:
`CMake Error at cmake/FindSDL2W.cmake:324 (message):
  SDL2W: SDL2 not found.`

**Comment by bibendovsky** [comment]
Don't touch SDL2_DIR, use SDL2W_SDL2_DIR instead.

1) For official development libraries set SDL2W_SDL2_DIR to the root directory with "include" and "lib" ones.
2) For custom builds point to the directory with CMake configuration files: SDL2Config.cmake, SDL2ConfigVersion.cmake, SDL2Targets.cmake, SDL2Targets-release.cmake.

**Comment by Uberwire** [comment]
Thanks!
