### ISSUE TITLE
Compile broken on VS 2019

### ISSUE THREAD

**Issue by lemming104** [bibendovsky/bstone#153]
I was able to build your project successfully on the previous version of the VS Community Edition, but on VS 2019, I encounter multiple build breaks (there are over 800, but these are the "root cause" ones)

`C2039	'string': is not a member of 'std' (compiling source file C:\git\bstone\src\3d_game.cpp)		C:\git\bstone\src\3d_def.h	2920`

`C2039	'uninitialized_copy_n': is not a member of 'std'	C:\git\bstone\src\bstone_memory_stream.cpp	316`

I was able to fix this locally, and obtain a working build, by adding the following include directives:
in 3d_def.h:  
`#include <string>`

in bstone_memory_stream.h
`#include <memory>`

**Comment by bibendovsky** [comment]
"develop" branch should be fixed now.

**Comment by lemming104** [comment]
Confirmed that it builds correctly on my environment now.
