### ISSUE TITLE
2 Minor Issues in Planetstrike with 1112

### ISSUE THREAD

**Issue by Stingm** [bibendovsky/bstone#155]
1. On level 2 I got the keys and found the secret level. The issue is when I came back they were gone from my inventory. This never happened in previous versions to my knowledge. 

2. Not a huge deal but I noticed that if you change a setting like mouse speed for example. When you go back to the game it freezes for a bit and makes beep sounds. It will run after a bit. 

I'm using the latest version of the source port 1112 on windows 10. Thanks for all your hard work on this source port. I really appreciate you doing this for all of us.

**Comment by bibendovsky** [comment]
1. Are you sure you didn't use the keys on the secret level? Do you have a saved game?

**Comment by Stingm** [comment]
That's a good question. I don't think I did.  I see your point though. 
I just went and played again and the keys were there in both levels. You must be right I must have used them and didn't know. Sorry about that. 
I guess thing are perfect then. I can live with the beeping as my settings won't be changed. Sorry to have wasted your time and thanks a bunch again.
