### ISSUE TITLE
Light effect is barely visible in high resolution modes

### ISSUE THREAD

**Issue by danpla** [bibendovsky/bstone#156]
The higher is resolution, the less is visible light effect. The first screenshot is taken with `--vid_windowed --vid_mode 320 240`; it looks the same as in DOSBox. The second one is `--vid_windowed --vid_mode 1200 900` downscaled to 320x240; it looks much brighter.
![2019-05-25-011928_322x267_scrot](https://user-images.githubusercontent.com/10910745/58359570-cc52a400-7e8c-11e9-812a-5712f6b254c1.png)
![2019-05-25-012101_1600x900_scrot](https://user-images.githubusercontent.com/10910745/58359591-e3919180-7e8c-11e9-9e01-7d7da7dec360.png)
bstone v1.1.12

**Comment by bibendovsky** [comment]
Will be fixed in the next release.

**Comment by bibendovsky** [comment]
Fixed in v1.2.0.
