### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by remussatala** [bibendovsky/bstone#178]
cmake .
-- The CXX compiler identification is GNU 9.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SDL2W: Found config.
-- SDL2W: Found targets.
CMake Error at cmake/FindSDL2W.cmake:217 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:19 (find_package)

-- SDL2W: Found version: 
CMake Error at /usr/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SDL2W: Found unsuitable version "", but required is at least
  "2.0.4" (found 1)
Call Stack (most recent call first):
  /usr/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSDL2W.cmake:260 (find_package_handle_standard_args)
  CMakeLists.txt:19 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/user/bstone-1.1.13/src/CMakeFiles/CMakeOutput.log".

________________
OS Arch Linux

Any suggestions or instructions?

**Comment by bibendovsky** [comment]
What version are you trying to compile?
(release v1.1.13, develop, other)

**Comment by bibendovsky** [comment]
Seems it's v1.1.13.

I see two options for now:
1. Use develop version.
2. Replace `src/cmake/FindSDL2W.cmake` with the latest one ([here](https://github.com/bibendovsky/cmake_sdl2w/tree/master/cmake) or [here](https://github.com/bibendovsky/bstone/tree/develop/src/cmake)).

**Comment by bibendovsky** [comment]
Fixed in v1.1.14.
