### ISSUE TITLE
Linux build fails with link error missing libpthread reference

### ISSUE THREAD

**Issue by tdicola** [bibendovsky/bstone#19]
Just grabbed the source and built it on Ubuntu 14.10 but ran into this error during linking:
```
Linking CXX executable bstone
/usr/bin/ld: CMakeFiles/bstone.dir/bstone_audio_mixer.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Looks like the makefile needs to add a -lpthread to the final linking command.  I'm not super familiar with CMake but if I change this bit in CMakeLists.txt below:
```
target_link_libraries(
    "${BSTONE_TARGET}"
    "${SDLMAIN_LIBRARY}"
    "${SDL2_LIBRARIES}"
)
```
And change it to reference the pthread library like:
```
target_link_libraries(
    "${BSTONE_TARGET}"
    "${SDLMAIN_LIBRARY}"
    "${SDL2_LIBRARIES}"
    "pthread"
)
```
Then it builds and links just fine.  Not sure that change would work with other platforms like windows, etc.  Perhaps it needs to be behind a platform-specific check to only add the pthread library on Linux systems.

**Comment by bibendovsky** [comment]
Added pthread to list of libraries for GCC (7c99ef09f51fb1829904d34205b2a1646a98bb01). Thanks!
