### ISSUE TITLE
Custom key bindings don't reload properly on start

### ISSUE THREAD

**Issue by lemming104** [bibendovsky/bstone#195]
I am on commit hash 41779689cd473acf134816be62fdc9b5933f2869, running a 64-bit build of BSTONE built using MSVC 2019 and SDL2 2.0.8.

I don't like using the default key mappings, so I usually change them.  If I look at the config file in AppData\Roaming\bibendovsky\bstone, I can confirm that my custom key bindings ARE saved.  However, the next time I launch the game, the key bindings are reset to their defaults.

I think this was introduced by something that was merged in the last few days, but since it looks like a *lot* of changes were recently merged into the trunk, I can't bisect down to the offending commit very easily.

**Comment by bibendovsky** [comment]
Please check branch `fix/195_input_bindings`.

**Comment by lemming104** [comment]
Yes, that seems to fix it.
