### ISSUE TITLE
Hitscans become more difficult with increased resolution

### ISSUE THREAD

**Issue by Blzut3** [bibendovsky/bstone#21]
Odd disclaimer: I haven't run the source port so I haven't personally experienced the issue as I don't have time to try it out at the moment.  I'm just going by what people are saying on Something Awful and various chats.  Even if the information below ends up not being helpful, I hope that reporting the bug to the issue tracker is. :)

From what I understand people are experiencing an issue where the "hitbox" for hit scans decreases with resolution increases.  I poked around the source code and I think I might know where the issue is coming from.  It looks like to handle increased resolution you implemented a scaling factor variable and attempt to keep viewwidth/viewheight based on 320x200.  The problem here is that the Wolf3D engine mixes rendition and physics.  The way the GunAttack function works is that it checks if the x position of the actor on screen is within shootdelta.  Shootdelta is viewwidth/10 or effectively 9 degrees giving an 18 degree cone to find eligible actors.  Off hand it looks like this doesn't get scaled, but I could be totally off.

**Comment by bibendovsky** [comment]
You are right. Value check->viewx in GunAttack is scaled. Fix d2d19fa5c89636f5ebac78a404a9568ad514c14c (aog3 branch) should eliminate the problem. Thanks for information!

**Comment by bibendovsky** [comment]
Fixed (c2f920f7169698e9552ffd3fd5dd95f51e16dbbf, d2d19fa5c89636f5ebac78a404a9568ad514c14c).
