### ISSUE TITLE
[Feature Request] Update Readme with build instructions

### ISSUE THREAD

**Issue by btegs** [bibendovsky/bstone#226]
I'm on Linux, so generally when pulling something from GitHub there is a makefile in the directory or something similar so I can easily make the binary. If there is a different step, I usually consult the readme file on specific instructions on how to build it.

For this project, I have no clue on how to compile the binary. Can you update the readme and add a makefile for those that are new to the project?

**Comment by bibendovsky** [comment]
You have to use CMake to generate makefile. This is indicated in section 5 of the README.
As a reference see #150 on how to compile in Linux-like system.

**Comment by btegs** [comment]
> You have to use CMake to generate makefile. This is indicated in section 5 of the README.
> As a reference see #150 on how to compile in Linux-like system.

Thanks for getting back to me regarding this. I recently wanted to give Blake Stone a try and came across your awesome project. I took a look at your link and will use that as a reference.

Since that is not in the main README, are you going to add those build steps to it in the near future? That would be great for those that do not know Cmake or don't compile from source that often and/or just want to jump into the game.

Also, have you considered adding a compiled Linux binary as a download next to the Windows ones in your releases? Could even use the `BSTONE_USE_STATIC_LINKING` flag to make the binary more portable.

**Comment by bibendovsky** [comment]
I have updated the README (#227).

> Also, have you considered adding a compiled Linux binary as a download next to the Windows ones in your releases?
I can't make any promises, but I'll see what I can do.
