### ISSUE TITLE
Does he have a virus?

### ISSUE THREAD

**Issue by remussatala** [bibendovsky/bstone#243]
Does he have a virus?
This is probably a false alarm from Microsoft.
https://drive.google.com/file/d/1IwlM7Fyovg0s4BM8gmHd_NnbPjnrE7W4/view?usp=sharing

v1.2.0-beta.5 win32

**Comment by bibendovsky** [comment]
On my computer Windows Defender does not trigger on that file.

Also here is a [report](https://www.virustotal.com/gui/file/a7924749090ac07e9b0f675f26aca1cc479aeac0cbf3cbf520353f08127873e2/detection) from VirusTotal for the package.
