### ISSUE TITLE
Blake Stone GOG Edition Auto-Detection?

### ISSUE THREAD

**Issue by MasterO2** [bibendovsky/bstone#260]
If you install a game on your computer via a GOG.com installer, sourceports for that game can often autodetect the install without you having to do anything else.

For example, if I install Doom 2's GOG edition with the GOG installer and I then run GZdoom, GZdoom will then detect that the GOG edition is installed on the system.

https://doomwiki.org/wiki/GOG.com#How_to_use_source_ports_with_games_downloaded_from_GOG.com

Would something like this be possible for both Blake Stone games?

**Comment by bibendovsky** [comment]
I'll see into such feature after v1.2.0.
Maybe not only for GOG.

**Comment by MasterO2** [comment]
> 
> 
> I'll see into such feature after v1.2.0.
> Maybe not only for GOG.

I also assume you will do that for Steam as well.  Same idea as what I said above.

**Comment by bibendovsky** [comment]
Added into upcoming minor release.

[bstone_bin_win32_v1_2_1.zip](https://github.com/bibendovsky/bstone/files/4611263/bstone_bin_win32_v1_2_1.zip)
[bstone_bin_win64_v1_2_1.zip](https://github.com/bibendovsky/bstone/files/4611265/bstone_bin_win64_v1_2_1.zip)
