### ISSUE TITLE
[Feature] Add a setting to allow the destruction of Plasma Alien Generator

### ISSUE THREAD

**Issue by Irv1n3** [bibendovsky/bstone#267]
Hello, I know it's a very specific request and maybe it's not possible to implement it but I'm asking anyway :)

I hate the plasma alien Generator, it's really annoying and it can make 100% run at the highest skill level stupidly difficult sometimes.

Can it be possible to make Generators destructible like volatile transports? (not by default obviously but via a setting)

Thanks for the answer!

**Comment by bibendovsky** [comment]
Hello.

This is definitely would be a cheat.
You may temporarily to enable invincibility to bypass such obstacles.

**Comment by Irv1n3** [comment]
Yeah, I'm doing a new run and it's ok, I'll manage to handle them!
