### ISSUE TITLE
Missing enemy/kill not registered?

### ISSUE THREAD

**Issue by Irv1n3** [bibendovsky/bstone#273]
Hi, I have a save of e4m8 with a missing kill but I can't find it.
The map is small and I went around it 4 times without finding anything.

Is it possible to check on the save if I miss something or if it's a bug?
Thanks!

[bstone_aog_full_saved_game_3.zip](https://github.com/bibendovsky/bstone/files/4638411/bstone_aog_full_saved_game_3.zip)

**Comment by bibendovsky** [comment]
Seems a bug.
Myabe because of wandering Dr. Goldfire in south-east location which was counted as enemy bu should not.

**Comment by bibendovsky** [comment]
Should be completable now with 100% rating in v1.2.4.
Unfortunately made changes break saved games compatibility.
