### ISSUE TITLE
Unnecessary update: [E4L1] Added missing barrier switch for 100% points.

### ISSUE THREAD

**Issue by Irv1n3** [bibendovsky/bstone#281]
Hello, thanks for the new version, I saw in the note this point
* [E4L1] Added missing barrier switch for 100% points.

The switch exists but it is located in the second level of the mission.
It forces the player to go back to the first floor and it's a bit annoying to search in the first floor when you don't know this but I think this change is not needed, the original game design allows the player to get 100% in this floor (but not in his first visit)

**Comment by bibendovsky** [comment]
Indeed. Found the switch at (51, 1).

**Comment by bibendovsky** [comment]
Thanks.
Removed in v1.2.5.
