### ISSUE TITLE
[VID] Applying texture upscale error

### ISSUE THREAD

**Issue by Exarkuniv** [bibendovsky/bstone#290]
I was able to get this to run great on my Pi3b running Retropie with Debian Stretch 4.14.98. but with the newest version it no longers want to launch. i dont know what version it was that was working before as it was install with a shell script and it was all auto. 

here is where it stops
``
[VID] Applying texture upscale.
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1255:  1832 Bus error               /opt/retropie/ports/bstone/bstone --data_dir /home/pi/RetroPie/roms/ports/bstone/aog
``

here is all of the data

``
Looking for game content.
Found "Blake Stone: Aliens Of Gold (shareware)" v3.0.
Content source: custom dir

Data path: "/home/pi/RetroPie/roms/ports/bstone/aog/"
Mod path: ""
Profile path: "/home/pi/.local/share/bibendovsky/bstone/"

[SND] Initializing audio
[SND] ------------------
[SND] Channel count: 2
[SND] Sample rate: 44100 Hz
[SND] Mix size: 40 ms
[SND] Effects volume: 10 / 20
[SND] Music volume: 5 / 20
[SND] OPL3 type: DosBox DBOPL
[SND] Resampling interpolation: Linear
[SND] Resampling low-pass filter: On

[VID] Initializing hardware accelerated video system.
[VID] Initializing task manager.
[VID] Creating renderer manager.
[VID] Getting display mode.

[VID] --------------------
[VID] Common configuration
[VID] --------------------
[VID] Renderer: auto-detect
[VID] Is windowed: true
[VID] Window positioned: false
[VID] Windowed x: 0
[VID] Windowed y: 0
[VID] Windowed width: 640
[VID] Windowed height: 480
[VID] UI stretched: false
[VID] Widescreen: true
[VID] 2D texture filter: nearest
[VID] 3D texture image filter: nearest
[VID] 3D texture mipmap filter: nearest
[VID] Texture anisotropy: 1
[VID] Texture upscale filter: none
[VID] Texture upscale xBRZ factor: 0
[VID] Anti-aliasing kind: none
[VID] Anti-aliasing value: 1
[VID] --------------------

[VID] Initializing 3D renderer.
[VID] Trying to initialize "OpenGL 3.2 core".
ERROR: [VID] [REN_3D_GL_UTL_MK_CTX_INIT] Failed.
[VID] Trying to initialize "OpenGL 2.0".

[VID] Device features
[VID] ===============
[VID] V-Sync: true
[VID] V-Sync requires restart: false
[VID] Texture max dimension: 4096
[VID] Viewport max width: 4096
[VID] Viewport max height: 4096
[VID] Anisotropy: false
[VID] Anisotropy max degree: 1
[VID] Non-power-of-two textures: true
[VID] Mipmap auto-generation: true
[VID] Samplers: true
[VID] MSAA: true
[VID] MSAA (render-to-window): false
[VID] MSAA requires restart: false
[VID] MSAA max degree: 4
[VID] Vertex input max locations: 16

[VID] Initializing shader program.
[VID] Initializing shader variables.

[VID] Creating texture manager.

[VID] Initializing 2D resources.
[VID] Creating UI index buffer.
[VID] Creating UI vertex buffer.
[VID] Creating UI vertex input.
[VID] Creating 2D filler index buffer.
[VID] Creating 2D filler vertex buffer.
[VID] Creating 2D filler vertex input.
[VID] Creating UI texture.
[VID] Creating 2D 1x1 black texture.
[VID] Creating 2D 1x1 white texture.
[VID] Creating 2D 1x1 fade texture.

[VID] Initializing 3D flooring.
[VID] Creating 3D flooring index buffer.
[VID] Creating 3D flooring vertex buffer.
[VID] Creating 3D flooring vertex input.
[VID] Creating 3D flooring 1x1 solid texture.

[VID] Initializing 3D ceiling.
[VID] Creating 3D ceiling index buffer.
[VID] Creating 3D ceiling vertex buffer.
[VID] Creating 3D ceiling vertex input.

[VID] Initializing 3D fade.
[VID] Creating 3D fade index buffer.
[VID] Creating 3D fade vertex buffer.
[VID] Creating 3D fade vertex input.
[VID] Create 3D fade texture.

[VID] Initializing player's weapon.
[VID] Creating player's weapon index buffer.
[VID] Creating player's weapon vertex buffer.
[VID] Creating player's weapon vertex input.
[VID] Creating player's weapon sampler.

[VID] Initializing command buffers.
[VID] Creating common command buffer.
[VID] Creating 3D command buffer.
[VID] Creating 2D command buffer.
[VID] Initializing command buffers.

[VID] Initializing samplers.
[VID] Creating UI sampler.
[VID] Creating sprite sampler.
[VID] Creating wall side sampler.
[VID] Creating fade sampler.

[VID] Applying texture upscale.
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1255:  5134 Bus error               SDL_VIDEO_KMSDRM_CRTCID=49 SDL_VIDEO_KMSDRM_MODEID=39 /opt/retropie/ports/bstone/bstone --data_dir /home/pi/RetroPie/roms/ports/bstone/aog
``

not sure why it is now stopping at this point. with your latest version. 
im working on trying to find out what version does work. i would love to get your latest version as you have done some very nice updates

UPDATE. anything older then 1.1.16 works fine. on my PI3
Im going to try on my PI4 and i will update again what i find since my Pi4 is running buster

**Comment by bibendovsky** [comment]
It's hard to say without debugging what exactly triggers the problem.
As a workaround set software renderer in configuration file (`vid_renderer "software"`) or in command line (`--vid_renderer software`).


> UPDATE. anything older then 1.1.16 works fine. on my PI3

Versions below 1.2.0 has only one renderer - software.

**Comment by Exarkuniv** [comment]
i did think that it was something with the renderer. and i did try the command befor with no luck.

this time i did try it by lunching it from command line, still same thing. gives me a bus error.

still looks like that it was still trying to use one of the OPENGLs.
i did try looking for the config file but i did not see anything in the folders


if there is anything that i could do to help i would gladly try. im not a progammer and new with compiling and getting things to work. but i would still give it a shot non the less

**Comment by bibendovsky** [comment]
Please attach the log with forced software renderer.

**Comment by Exarkuniv** [comment]
hope this is what you mean

``
pi@retropie:~/bstone/build $ ./bstone --vid_renderer software
BStone v1.2.8

Looking for game content.
Found "Blake Stone: Aliens Of Gold (shareware)" v3.0.
Content source: working dir

Data path: "/home/pi/bstone/build/"
Mod path: ""
Profile path: "/home/pi/.local/share/bibendovsky/bstone/"

[SND] Initializing audio
[SND] ------------------
[SND] Channel count: 2
[SND] Sample rate: 44100 Hz
[SND] Mix size: 40 ms
[SND] Effects volume: 10 / 20
[SND] Music volume: 5 / 20
[SND] OPL3 type: DosBox DBOPL
[SND] Resampling interpolation: Linear
[SND] Resampling low-pass filter: On

[VID] Initializing hardware accelerated video system.
[VID] Initializing task manager.
[VID] Creating renderer manager.
[VID] Getting display mode.

[VID] --------------------
[VID] Common configuration
[VID] --------------------
[VID] Renderer: auto-detect
[VID] Is windowed: true
[VID] Window positioned: false
[VID] Windowed x: 0
[VID] Windowed y: 0
[VID] Windowed width: 640
[VID] Windowed height: 480
[VID] UI stretched: false
[VID] Widescreen: true
[VID] 2D texture filter: nearest
[VID] 3D texture image filter: nearest
[VID] 3D texture mipmap filter: nearest
[VID] Texture anisotropy: 1
[VID] Texture upscale filter: none
[VID] Texture upscale xBRZ factor: 0
[VID] Anti-aliasing kind: none
[VID] Anti-aliasing value: 1
[VID] --------------------

[VID] Initializing 3D renderer.
[VID] Trying to initialize "OpenGL 3.2 core".
ERROR: [VID] [REN_3D_UTL_CREATE_WND] Failed.
[VID] Trying to initialize "OpenGL 2.0".
ERROR: [VID] [REN_3D_UTL_CREATE_WND] Failed.
[VID] Trying to initialize "OpenGL ES 2.0".

[VID] Device features
[VID] ===============
[VID] V-Sync: true
[VID] V-Sync requires restart: false
[VID] Texture max dimension: 2048
[VID] Viewport max width: 2048
[VID] Viewport max height: 2048
[VID] Anisotropy: false
[VID] Anisotropy max degree: 1
[VID] Non-power-of-two textures: true
[VID] Mipmap auto-generation: true
[VID] Samplers: true
[VID] MSAA: false
[VID] MSAA (render-to-window): false
[VID] MSAA requires restart: false
[VID] MSAA max degree: 1
[VID] Vertex input max locations: 8

[VID] Initializing shader program.
[VID] Initializing shader variables.

[VID] Creating texture manager.

[VID] Initializing 2D resources.
[VID] Creating UI index buffer.
[VID] Creating UI vertex buffer.
[VID] Creating UI vertex input.
[VID] Creating 2D filler index buffer.
[VID] Creating 2D filler vertex buffer.
[VID] Creating 2D filler vertex input.
[VID] Creating UI texture.
[VID] Creating 2D 1x1 black texture.
[VID] Creating 2D 1x1 white texture.
[VID] Creating 2D 1x1 fade texture.

[VID] Initializing 3D flooring.
[VID] Creating 3D flooring index buffer.
[VID] Creating 3D flooring vertex buffer.
[VID] Creating 3D flooring vertex input.
[VID] Creating 3D flooring 1x1 solid texture.

[VID] Initializing 3D ceiling.
[VID] Creating 3D ceiling index buffer.
[VID] Creating 3D ceiling vertex buffer.
[VID] Creating 3D ceiling vertex input.

[VID] Initializing 3D fade.
[VID] Creating 3D fade index buffer.
[VID] Creating 3D fade vertex buffer.
[VID] Creating 3D fade vertex input.
[VID] Create 3D fade texture.

[VID] Initializing player's weapon.
[VID] Creating player's weapon index buffer.
[VID] Creating player's weapon vertex buffer.
[VID] Creating player's weapon vertex input.
[VID] Creating player's weapon sampler.

[VID] Initializing command buffers.
[VID] Creating common command buffer.
[VID] Creating 3D command buffer.
[VID] Creating 2D command buffer.
[VID] Initializing command buffers.

[VID] Initializing samplers.
[VID] Creating UI sampler.
[VID] Creating sprite sampler.
[VID] Creating wall side sampler.
[VID] Creating fade sampler.

[VID] Applying texture upscale.
Bus error
pi@retropie:~/bstone/build $
``

**Comment by bibendovsky** [comment]
Command-line option does not work (it's a bug) but configuration file does.
Set correct value (`software`) directly in th configuration file (`bstone_config.txt`).
Key name is same - `vid_renderer`.

**Comment by Exarkuniv** [comment]
thank you for that, 
not to sound stupid but i cant find the config.txt anywhere.
i did build it from source and that went fine but i dont see it

i even did a search of my whole card. never found a `bstone_config.txt` anywhere

**Comment by bibendovsky** [comment]
> not to sound stupid but i cant find the config.txt anywhere.

For example, from your last log:
`Profile path: "/home/pi/.local/share/bibendovsky/bstone/"`

**Comment by Exarkuniv** [comment]
i did look there but the only thing there is `bstone_log.txt` 

which remains empty even if i tried to start the game

**Comment by bibendovsky** [comment]
In that case just create a file `bstone_config.txt` in this directory.
Content of this file should be one line - `vid_renderer "software"`.

**Comment by Exarkuniv** [comment]
well i made `bstone_config.txt` as you said. with 
`- vid_renderer "software"` being the only line in it. 
i put it in a few places

`/home/pi/.local/share/bibendovsky/bstone/`
`/home/pi/bstone`
`/home/pi/bstone/build`

and nothing. it is still saying `Renderer: auto-detect`
and comming up with `Bus Error` at the end

**Comment by bibendovsky** [comment]
> `- vid_renderer "software"` being the only line in it.

I hope the line does not start with a dash?


> `/home/pi/.local/share/bibendovsky/bstone/`
> `/home/pi/bstone`
> `/home/pi/bstone/build`

You don't have to place the file into several directories. The first one enough.
Additionally you may point a location with command line `--profile_dir path_to_dir`.

Attached a [sample file](https://github.com/bibendovsky/bstone/files/4939117/bstone_config.txt) for reference.

**Comment by Exarkuniv** [comment]
i saw my problem. i was missing a "
thank you for all your help
 its all good now

did find out why the config file was missing. it was never made. the program was crashing before it even had a chance to make the config file.
