### ISSUE TITLE
Use more than two sound channels

### ISSUE THREAD

**Issue by NightFright2k19** [bibendovsky/bstone#293]
It happens often that playing sounds are interrupted by newer ones, e.g. when collecting multiple loot or shooting several enemies in a row. This is most likely due to the 2-channel sound limitation of the game and could probably be fixed if more channels were available. If it is technically possible, it would probably make sense to turn this into an option in the sound menu since it deviates from vanilla behavior.

**Comment by bibendovsky** [comment]
I don't understand the problem. You want to add an option to control the playback interruption of looting items only?

Vanilla engine interrups new sounds (like loot items) as well and even more - it can't playback multiple sounds at-once. There is a prioritization system which selects most important sounds.

Try to hold the trigger of automatic weapon while enemy is dying, you wont hear the weapon and other sounds while "dying" sound is playing.

The port, on the other hand, indeed uses _mostly_ two channels _per actor / object_, so called "voice" and "weapon". An exception is the player which has several extra channels. But it _can_ playback multiple sounds at-once.
