### ISSUE TITLE
Plasma Alien spawner

### ISSUE THREAD

**Issue by NightFright2k19** [bibendovsky/bstone#296]
The spawnrates of the Plasma Alien spawners seem extreme. On normal difficulty ("Skilled Agent"), a new Plasma Alien is spawned often within 1-3 seconds after you destroyed the previous one. This seems too fast since it will result in you becoming quickly overwhelmed in a room with 2 spawners or even more, regardless of difficulty setting.

**Comment by bibendovsky** [comment]
Default delay between spawns is `8 + random(22)` units. One unit is `0.857` seconds (`60 / 70` seconds to be pricese). So the range is from `6.9` seconds to `25.7` seconds.

Some maps may override this delay.
For example, E4M2 has two spawners (`(48, 6)` and `(44, 10)`) with delay set to `1` unit.

**Comment by NightFright2k19** [comment]
Well, if it's supposed to be like that, no need to change, I guess. I just don't remember it being so hard, but I guess it's just like that in E4M2. There are two rooms where you have to run through really fast, otherwise you die quickly.

**Comment by bibendovsky** [comment]
The difficulty affects an amount of alive aliens per generator.
For example, on difficulty level 1 the generator will spawn another alien only if amount of alive aliens spawned by this generator less than one. On difficulty level 2 this will be two alive aliens and so on.

**Comment by NightFright2k19** [comment]
OK, then I guess I just screwed myself by choosing "Skilled Agent". Good to know it makes a difference, though!
