### ISSUE TITLE
Collect keycards of same color

### ISSUE THREAD

**Issue by NightFright2k19** [bibendovsky/bstone#298]
It would be a nice comfort feature (maybe as a menu option) to be able to collect more than one keycard of the same color.
While this is not relevant for the original episodes, it would come in handy for the user-made episodes (e.g. BSE90) where it would eliminate some otherwise necessary backtracking.

**Comment by bibendovsky** [comment]
> It would be a nice comfort feature (maybe as a menu option)

Such option may confuse the user since it impossible always to apply it immediately for gameplay.
