### ISSUE TITLE
Build fails when libSDL2main.a is missing.

### ISSUE THREAD

**Issue by orbea** [bibendovsky/bstone#303]
OS: `Slackware64-current`
bstone: https://github.com/bibendovsky/bstone/commit/42027a4307389b9953f752b2a4f7cc290c7cb400
SDL2: `2.0.12`

When building bstone it fails.
```
Scanning dependencies of target bstone
make[2]: *** No rule to make target '/usr/lib64/libSDL2main.a', needed by 'bstone'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[  0%] Building CXX object CMakeFiles/bstone.dir/cmake_pch.hxx.pch
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/bstone.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
This is because Slackware uses SDL2's autotools build which doesn't install `libSDL2main.a`, but even when using the upstream `sdl2-config.cmake` it fails in the same way...

I was able to work around this by using the `FindSDL2.cmake` from ppsspp instead.

https://github.com/hrydgard/ppsspp/blob/254c316b108a161e7d14d0c787489d0df16437ba/cmake/Modules/FindSDL2.cmake

**Comment by bibendovsky** [comment]
I can't reproduce the issue.
Built without problems.
Here is a [log](https://github.com/bibendovsky/bstone/files/5434495/bstone_303_slack_64_current_log_20201025121000.txt).

**Comment by orbea** [comment]
Sorry I was not clear enough. This is only Slackware current (And eventually will be in the next release if that is ever made).

In Slackware 14.2 SDL2 is only available at slackbuilds.org and is built with cmake, it does not have this problem. In current SDL2 was added to the main Slackware tree and is built with autotools, it does have this problem.

**Comment by orbea** [comment]
It should be possible to reproduce it on Slackware 14.2 by building SDL2 with this script.

https://mirrors.slackware.com/slackware/slackware64-current/source/l/SDL2/

Looking at the SDL2.SlackBuild it seems to be partially a Slackware problem.
```
# Don't package the static libraries:
( cd $PKG/usr/lib${LIBDIRSUFFIX}
  for file in *.so ; do
    rm -f $(basename $file .so).a
  done
)
```
That said even when replacing this with the `--disable-shared` configure argument it will still contain references to static libraries that are not created in its default `sdl2-config.cmake`.

So this its also problematic that `sdl2-config.cmake` and `FindSDL2W.cmake` in bstone depend on static libraries existing. The `FindSDL2.cmake` from ppsspp does not have this problem, it might be as easy to solve this by borrowing it and replacing the current `FindSDL2W.cmake`?

**Comment by bibendovsky** [comment]
> Sorry I was not clear enough. This is only Slackware current (And eventually will be in the next release if that is ever made).

The log above is from Slackware 64 _current (development)_ not the _14.2 stable_ one.

**Comment by bibendovsky** [comment]
> So this its also problematic that `sdl2-config.cmake` and `FindSDL2W.cmake` in bstone depend on static libraries existing.

FindSDL2W.cmake gets include directories and library list from SDL2's CMake targets.
Those targets are: `SDL2::SDL2` or `SDL2::SDL2-static` (usually on Windows only), and `SDL2::SDL2main`.
If one of them contains invalid location this may cause a problem.

**Comment by orbea** [comment]
You are right. For some reason my SDL2 package was broken and missing static libraries...

Sorry for the noise and thanks for the time.
