### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by vrbandwagon** [bibendovsky/bstone#310]
I was wondering if gamepad support is planned.

**Comment by bibendovsky** [comment]
Yes, it's planned but I doubt it happens in this year.
Similar questions (like #76) arised in past years.
Only recently I got my hands on hardware (Xbox One controller).

**Comment by vrbandwagon** [comment]
Thank you for the quick response.
Understood. I'll keep an eye out then.

**Comment by NJW1979** [comment]
In the interim there is a free program called Antimicro that allows one to map keyboard and mouse actions to a gamepad.  I use it and it has less input lag that paid mapping programs like Pinnacle Game Profiler.

You can get Antimicr her on Github: https://github.com/AntiMicro/antimicro

**Comment by vrbandwagon** [comment]
> In the interim there is a free program called Antimicro that allows one to map keyboard and mouse actions to a gamepad. I use it and it has less input lag that paid mapping programs like Pinnacle Game Profiler.
> 
> You can get Antimicr her on Github: https://github.com/AntiMicro/antimicro

Great find. Thank you!

**Comment by NJW1979** [comment]
You are very welcome.  Make sure when you set the right stick as the mouse set a ridiculous sensitivity or yoou will turn too slowly.  Mine is set at 250X + 250Y under mouse settings.

**Comment by vrbandwagon** [comment]
Will do!
