### ISSUE TITLE
Aliens of Gold oddities with latest version 1.29?

### ISSUE THREAD

**Issue by Stingm** [bibendovsky/bstone#311]
1. I have noticed that every now and again a scientist is frozen in the level. He just stands there and you can't use him or anything. 
2. I have noticed that with the creatures that hatch from the eggs that the hatching animation plays twice in a row before you can shoot them. Again this isn't constant just every once in a while. 
Neither of these is game breaking and I still love playing your source port.

Thanks for the hard work.

Stingm

**Comment by bibendovsky** [comment]
1. If someone has saved game with "frozen" actors please attach it here on send by email.

**Comment by bibendovsky** [comment]
@Stingm Does scientists got frozen in the [latest release](https://github.com/bibendovsky/bstone/releases/tag/v1.2.12)?

**Comment by bibendovsky** [comment]
Closing for now.
Feel free to reopen the issue if the problem still persisted.

[bstone_v1.2.13-wip-i686-099dde62df583b58b8cc9ff06ac7791628696ce5.zip](https://github.com/bibendovsky/bstone/files/14536999/bstone_v1.2.13-wip-i686-099dde62df583b58b8cc9ff06ac7791628696ce5.zip)
[bstone_v1.2.13-wip-x86_64-099dde62df583b58b8cc9ff06ac7791628696ce5.zip](https://github.com/bibendovsky/bstone/files/14537000/bstone_v1.2.13-wip-x86_64-099dde62df583b58b8cc9ff06ac7791628696ce5.zip)
