### ISSUE TITLE
Possible issue in the extra lives system (only trigger once)

### ISSUE THREAD

**Issue by Irv1n3** [bibendovsky/bstone#313]
Hello, I was reading for fun the games manuals on Steam
AoG: https://steamcdn-a.akamaihd.net/steam/apps/358190/manuals/Manual.PDF?t=1567673353
PS: https://steamcdn-a.akamaihd.net/steam/apps/358310/manuals/Manual.PDF?t=1567672744

And notice in the score display section of AoG the mention "Every 400,000 points provides an extra life.".
It's said again in the description of the Xylan Orb (both in AoG manual and PS): "Remember with every 400,000 points you are awarded an extra life.".

However, when I played my full run I was capped at 4 lives with only one extra life. 
I don't really play with the lives system but it could be worth checking.
Note that I played on the version 1.2.2, sorry if it got fixed since!

**Comment by bibendovsky** [comment]
> However, when I played my full run I was capped at 4 lives with only one extra life.
You have to lower lives counter and collect enough bonus items to hit internal points counter in order to receive another extra live.
