### ISSUE TITLE
Strange fade in/out when starting a new game

### ISSUE THREAD

**Issue by emileb** [bibendovsky/bstone#318]
Hi, great work on this - I am porting to Android I hope that is OK!

Seems to working great, but there is one small strange thing when starting a new game in OpenGL mode - It does quite a strange fade in/fade out and flickering thing. On one fade in/fade out it seems to just show the floor/ceiling. This does not occur in SW mode.
I am happy to take a look at fixing it, before I start I am just wondering if you have tried to fix it and it is actually quite difficult to fix? Or maybe have a hint for me to start looking?

Thank for your work on these games.

**Comment by bibendovsky** [comment]
> I am happy to take a look at fixing it, before I start I am just wondering if you have tried to fix it and it is actually quite difficult to fix? Or maybe have a hint for me to start looking?

Since it happens only when starting the new game I did not pay too much attention for this problem.
Could be wrong value of one of `vid_is_...` flag (`vid_is_hud`, `vid_is_3d`, etc. in `id_vl.cpp`) for "new game" context.

**Comment by emileb** [comment]
OK this seems to fit it for me on GLES2 (SW still works). Possible it could break some other part of the game.
It also fixes the screen fade when in widescreen and 3d view is showing.

https://github.com/emileb/bstone/commit/5ef36f1b7f2c39cd93968ed1a25ff00eb43031fa

**Comment by bibendovsky** [comment]
Works fine.
But why to keep bugged code for non-mobile platforms?

**Comment by emileb** [comment]
> Works fine.
> But why to keep bugged code for non-mobile platforms?

Great! Oh yes sorry I forgot to say, remove the __MOBILE__, I just use that on my 'mobile' branch so I can easily keep track of my deltas between upstream. I'll do a clean pull-req soon. Thanks for trying it out.

**Comment by bibendovsky** [comment]
Fixed in v1.2.10.
