### ISSUE TITLE
Planet Strike crashes when returning to level 1

### ISSUE THREAD

**Issue by Gengar0094** [bibendovsky/bstone#322]
So far, any other level is fine to backtrack. Only level one seems to crash when trying to reenter it after completing it and collecting at least one key from any level afterward. When returning to level one an error message will display once it crashes. 
"CRITICAL: [BARR_DEC_IDX] Level index out of range."

**Comment by bibendovsky** [comment]
Fixed (#323).
Please let me know if the provided beta below still has the issue.

[bstone_bin_win32_v1_2_10_beta_202101231239.zip](https://github.com/bibendovsky/bstone/files/5860046/bstone_bin_win32_v1_2_10_beta_202101231239.zip)
[bstone_bin_win64_v1_2_10_beta_202101231239.zip](https://github.com/bibendovsky/bstone/files/5860048/bstone_bin_win64_v1_2_10_beta_202101231239.zip)

**Comment by Gengar0094** [comment]
The issue is fixed now and no longer shows up. Tried it with both win32 and win64.
