### ISSUE TITLE
Note: Filename casing

### ISSUE THREAD

**Issue by Lewiscowles1986** [bibendovsky/bstone#327]
Thanks for making this. A Friend was asking about this, and I'm guessing they had trouble.

I Unpacked everything, installed and it seems that AOG files can come lowercase or uppercase. On case-sensitive systems, this can make a difference.

Would you be open to a troubleshooting section, with a filename casing entry?

**Comment by bibendovsky** [comment]
The port supports resource file names with *all* lowercase / uppercase characters (like, `AUDIOT.BS6` and `audiot.bs6`). Does your resource file names are in mixed case (i.e. `AudioT.Bs6`)?

**Comment by Lewiscowles1986** [comment]
Unfortunately they were all lowercase and didn't work until made all uppercase.

There was no mixture of casing.

It's likely that again, this is because my filesystem is case-sensitive.

This was under Ubuntu 20.04.

**Comment by bibendovsky** [comment]
Fix (#328) applied for `develop` branch.

**Comment by Lewiscowles1986** [comment]
Nice one 👍 I was just thinking we add to documentation, but you rock 🚀 🎸

**Comment by bibendovsky** [comment]
I'll update docs with information about file name restrictions before releasing v1.2.10.
Thanks for mention.

**Comment by bibendovsky** [comment]
Fixed in v1.2.10.
