### ISSUE TITLE
CMake fails to "Configure" on Windows 10 when using SDL2-2.0.14

### ISSUE THREAD

**Issue by Patrol1985** [bibendovsky/bstone#331]
The exact error message reads:

CMake Error at D:/programs/cmake-3.19.5-win64-x64/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find SDL2W: Found unsuitable version "", but required is at least
  "2.0.4" (found 1)

I am attaching a screenshot from the CMake GUI.

I tried to use the following tools for compilation:
- g++ compiler ver. 8.1.0 (contained in MinGW-W64)
- CMake 3.19.5 for Windows
- SDL2 2.0.14 development library

![BStone_SDL2_error_2021-02-17](https://user-images.githubusercontent.com/6830489/108206132-46799080-7126-11eb-9e5b-7cebae34b964.JPG)

New screenshot as per comment:

![BStone_SDL2_error_2021-02-17_02](https://user-images.githubusercontent.com/6830489/108256998-7f355c00-715e-11eb-95d7-9d92f5670776.JPG)

Screenshot from the CLI version of CMake as per comment:

![BStone_SDL2_error_2021-02-17_03](https://user-images.githubusercontent.com/6830489/108263785-fb33a200-7166-11eb-8362-4113b979d0bf.JPG)

Screenshot from VS Code execution of CMake as per comment:

![BStone_SDL2_error_2021-02-17_04](https://user-images.githubusercontent.com/6830489/108263844-0b4b8180-7167-11eb-9923-710a462777e3.JPG)

**Comment by bibendovsky** [comment]
Set `SDL2W_SDL2_DIR` variable to `D:/programs/SDL2-2.0.14`.

**Comment by Patrol1985** [comment]
I did as instructed. The same error occurred, but some things changed:
1. The variables are no longer highlighted in red
2. CMAKE_BUILD_TYPE received a value ("Release")
3. CMAKE_C_COMPILER appeared and received a value (pointing to gcc.exe)
4. SDL2_DIR returned "SDL2_DIR-NOTFOUND"

I will attach a new screenshot from my CMake GUI.

**Comment by bibendovsky** [comment]
Did you get MinGW development package from http://libsdl.org/?

**Comment by Patrol1985** [comment]
Yes, that is the exact package I downloaded and am using: SDL2-devel-2.0.14-mingw.tar.gz (MinGW 32/64-bit)

**Comment by bibendovsky** [comment]
What about non-GUI version of CMake?

**Comment by Patrol1985** [comment]
The non-GUI version returns an error regarding the compiler. It appears it cannot find it even though it is properly set in the path. It seems that CMake is looking specifically for the "cl" compiler (whatever it may be) and it tells me to run it from the Visual Studio Command Prompt. I do not have visual studio, but I have VS Code, which I configured to make use of both CMake and the g++ compiler. However, VS Code returns the same error as originally reported. I will paste two more screenshots showing messages from the command prompt and VS Code.

**Comment by bibendovsky** [comment]
In the file `src/cmake/FindSDL2W.cmake` at line 303 replace

```
		execute_process (
			COMMAND "sh" "-c" "cmd //c echo ${SDL2W_TMP_SDL_VERSION_H}"
			TIMEOUT 7
			OUTPUT_VARIABLE SDL2W_TMP_SDL_VERSION_H
			ERROR_QUIET
			OUTPUT_STRIP_TRAILING_WHITESPACE
		)
```

with

```
		unset (SDL2W_TMP_SDL_VERSION_H_MSYS2)

		execute_process (
			COMMAND "sh" "-c" "cmd //c echo ${SDL2W_TMP_SDL_VERSION_H}"
			TIMEOUT 7
			OUTPUT_VARIABLE SDL2W_TMP_SDL_VERSION_H_MSYS2
			ERROR_QUIET
			OUTPUT_STRIP_TRAILING_WHITESPACE
		)

		if (SDL2W_TMP_SDL_VERSION_H_MSYS2 MATCHES "SDL_version\\.h$")
			set (SDL2W_TMP_SDL_VERSION_H ${SDL2W_TMP_SDL_VERSION_H_MSYS2})
		endif ()
```

**Comment by Patrol1985** [comment]
It worked! Thank you for the solution. I received a different error when compiling, but I will create a separate entry about it. As far as the "configure" step goes, this one is solved. Thank you again! I'm not sure what the rules are here (I'm new to GitHub and this is the first project I have commented on) and if I should close this entry so I will leave it open. If such solved issues should be closed by their creators, please let me know in a comment.

**Comment by bibendovsky** [comment]
In this case you may leave the issue open.
I'll hook it to upcoming fix.
Once the fix will be integrated into a branch the issue close automatically.
