### ISSUE TITLE
Error when compiling the source on Windows 10 (concerns "gt_pch_note_object")

### ISSUE THREAD

**Issue by Patrol1985** [bibendovsky/bstone#332]
Upon compiling the source I received the following error:

```
D:/games/bstone-develop/src/bstone_ren_3d_limits.h:53:1: internal compiler error: in gt_pch_note_object, at ggc-common.c:276
```

A few more error messages appeared, but I am not sure if they do not simply stem from the first one. I'm pasting the whole log below:

```
[main] Building folder: src 
[build] Starting build
[proc] Executing command: D:\programs\cmake-3.19.5-win64-x64\bin\cmake.EXE --build d:/games/bstone-develop/src/build --config Release --target all -- -j 10
[build] [  0%] Building CXX object CMakeFiles/bstone.dir/cmake_pch.hxx.gch
[build] In file included from D:/games/bstone-develop/src/bstone_precompiled.h:90,
[build]                  from D:/games/bstone-develop/src/build/CMakeFiles/bstone.dir/cmake_pch.hxx:5,
[build]                  from <command-line>:
[build] D:/games/bstone-develop/src/bstone_ren_3d_limits.h:53:1: internal compiler error: in gt_pch_note_object, at ggc-common.c:276
[build]  } // bstone
[build]  ^
[build] libbacktrace could not find executable to open
[build] Please submit a full bug report,
[build] with preprocessed source if appropriate.
[build] See <https://sourceforge.net/projects/mingw-w64> for instructions.
[build] mingw32-make.exe[2]: *** [CMakeFiles\bstone.dir\build.make:83: CMakeFiles/bstone.dir/cmake_pch.hxx.gch] Error 1
[build] mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:94: CMakeFiles/bstone.dir/all] Error 2
[build] mingw32-make.exe: *** [Makefile:148: all] Error 2
[build] Build finished with exit code 2
```

Tools I used for the compilation:
- VS Code ver. 1.53.2
- g++ compiler ver. 8.1.0 (contained in MinGW-W64)
- CMake 3.19.5 for Windows

**Comment by bibendovsky** [comment]
It seems the support of precompiled headers in this version by the compiler is broken .
Try to turn off the precompiled headers with `BSTONE_USE_PCH` variable.

**Comment by Patrol1985** [comment]
It worked! I edited the file src\build\CMakeCache.txt and changed the BSTONE_USE_PCH variable to OFF as instructed. The source port compiled successfully - thank you for the help!

**Comment by bibendovsky** [comment]
You don't have to edit `CMakeCache.txt` to modify the variable.
Just pass appropriate parameter to CMake: `cmake -DBSTONE_USE_PCH=OFF`

**Comment by Patrol1985** [comment]
Thank you for the tip. For some reason when I try to use CMake via the command line it does not work as intended - I probably didn't configure something properly or forgot to pass additional parameters (I'm still learning how to use the tool). However, when I linked it to VS Code everything went fine, but in this interface I do not know how to pass parameters manually and that's why editing the `CMakeCache.txt` file worked for me. Either way, the problem is solved - thank you again.
