### ISSUE TITLE
Screenshot functionality

### ISSUE THREAD

**Issue by chbrehm** [bibendovsky/bstone#334]
It would be a nice enhancement if the port had a built-in hotkey for saving a screenshot.

**Comment by bibendovsky** [comment]
The feature added to the `devel` branch.

Default key <kbd>F5</kbd>.
Use menu `GAME OPTIONS - CONTROLS - CUSTOMIZE CONTROLS` to modify it.

All screenshots are goes into profile directory.
To change directory pass it to command-line: `bstone.exe --screenshot_dir dir/with/my/shots`.
The path *must* exist.

Here are Windows builds for testing:
[bstone_bin_win32_v1_2_11_beta_9e8a8e9.zip](https://github.com/bibendovsky/bstone/files/6097540/bstone_bin_win32_v1_2_11_beta_9e8a8e9.zip)
[bstone_bin_win64_v1_2_11_beta_9e8a8e9.zip](https://github.com/bibendovsky/bstone/files/6097541/bstone_bin_win64_v1_2_11_beta_9e8a8e9.zip)

**Comment by chbrehm** [comment]
Thank you for implementing this. I've just tested it with the GOG version of AOG. The screenshots get saved, but they are very distorted. I'll attach one. I'm playing at 2560x1440, which is my monitor's native resolution.
![bstone_aog_sshot_20210307_180346_429](https://user-images.githubusercontent.com/28632515/110248101-5c30e780-7f67-11eb-9f79-2dd59357fc2f.png)

**Comment by bibendovsky** [comment]
Does all type of renderers causes this?

**Comment by chbrehm** [comment]
I had the renderer set to auto-detect before. I've just retested it with each of the renderers.

With each of the three GL renderers (2.0, 3.2, and GLES 2.0) it looks distorted like in the attachment before.

With the software renderer, the image is not distorted, but the screenshot only covers part of the image size. I'll attach a screenshot for this.

![bstone_aog_sshot_20210307_185355_337_software](https://user-images.githubusercontent.com/28632515/110249619-dfa20700-7f6e-11eb-8822-f4e51b80c509.png)

**Comment by bibendovsky** [comment]
New build creates additional data for diagnostic.
Please make two screenshots (main menu would be enough) for two renderers (`auto-detect` and `software`).
Archive four `issue_334_*.data` files and email them (or attach here).

[bstone_bin_win32_v1_2_11_beta_dbbcd3f.zip](https://github.com/bibendovsky/bstone/files/6102260/bstone_bin_win32_v1_2_11_beta_dbbcd3f.zip)
[bstone_bin_win64_v1_2_11_beta_dbbcd3f.zip](https://github.com/bibendovsky/bstone/files/6102261/bstone_bin_win64_v1_2_11_beta_dbbcd3f.zip)

**Comment by chbrehm** [comment]
I've made two screenshots for auto-detect and software and put the four data files in the attached zip.

[issue334.zip](https://github.com/bibendovsky/bstone/files/6102570/issue334.zip)

**Comment by bibendovsky** [comment]
Does your display scaling is 125%?

**Comment by chbrehm** [comment]
Yes it is indeed. (I wasn't aware that could affect games, I thought it applies only to software that uses GDI.)

**Comment by bibendovsky** [comment]
Could you test the functionality with 100% scaling?

**Comment by chbrehm** [comment]
I've just retested it with 100% scaling set in Windows.

Now the screenshots are fine both with software and auto-detect (OpenGL) renderer.

**Comment by chbrehm** [comment]
Some additional info, I don't know if it's relevant: I'm running Windows 10 20H2 (Build 19042.804). Graphics driver is Nvidia 461.72.

**Comment by bibendovsky** [comment]
Made the application DPI aware - there is no need to set compatibility (I hope).

[bstone_bin_win32_v1_2_11_beta_9a1304b.zip](https://github.com/bibendovsky/bstone/files/6109539/bstone_bin_win32_v1_2_11_beta_9a1304b.zip)
[bstone_bin_win64_v1_2_11_beta_9a1304b.zip](https://github.com/bibendovsky/bstone/files/6109541/bstone_bin_win64_v1_2_11_beta_9a1304b.zip)
