### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [bibendovsky/bstone#336]
**FOV Control:** Allow players to change FOV (maybe limiting to 90-130 range?).

**Disable weapon bobbing (for Planet Strike):** Maybe that's a good option since some people may be used to disable it when playing other FPS's.

**Comment by bibendovsky** [comment]
Added option to control weapon bobbing (#342).

**Comment by bibendovsky** [comment]
Added separate [issue](#434) for FOV control.
Weapon bobbing control got available since [v.1.2.12](https://github.com/bibendovsky/bstone/releases/tag/v1.2.12).
