### ISSUE TITLE
Launcher bug

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [bibendovsky/bstone#337]
Planet Strike is launched instead of Aliens of Gold after clicking its button on the launcher. I'm playing on Manjaro Linux KDE 20.2.1 using Wine Staging 6.2.

**Comment by bibendovsky** [comment]
> using Wine Staging 6.2

You are running Windows build via WINE?

**Comment by WilliamWeberBerrutti** [comment]
Yes I am.

**Comment by bibendovsky** [comment]
Fixed (#349).

Here are builds to test:
[bstone_bin_win32_v1_2_11_beta_0dda135.zip](https://github.com/bibendovsky/bstone/files/6136589/bstone_bin_win32_v1_2_11_beta_0dda135.zip)
[bstone_bin_win64_v1_2_11_beta_0dda135.zip](https://github.com/bibendovsky/bstone/files/6136590/bstone_bin_win64_v1_2_11_beta_0dda135.zip)
