### ISSUE TITLE
Savegames from Map Pack can't be loaded after exiting the game.

### ISSUE THREAD

**Issue by lemonsplash** [bibendovsky/bstone#348]
I'm playing some mappack which I've loaded with the --mod_dir command. (MAPHEAD.BS6 + MAPTEMP.BS6 in a separate folder)

Quicksaving and quickloading went fine but as soon as I've completely exited the game and tried to load my savegame again, it says that the saved game can't be loaded because of an unsupported version of the game.

Edit: Workaround: Starting a new game, then loading the saved game.
Edit2: Well, for some reason it doesn't work 100%

**Comment by bibendovsky** [comment]
Please email or attach here the log file.

**Comment by lemonsplash** [comment]
"ERROR: LOAD: Levels hash mismatch.
ERROR: LOAD: Failed to deserialize HEAD data. Levels hash mismatch."

Actually I don't know what went wrong. I warped back to the level of my savegame with cheats since I only had that one and now everything seems to be fine. File size of the savefile was like 40KB, now the savegame has 24KB, don't know.
I think this can be closed. :)

**Comment by bibendovsky** [comment]
> "ERROR: LOAD: Levels hash mismatch.
> ERROR: LOAD: Failed to deserialize HEAD data. Levels hash mismatch."

That means you saved the game with one map set (`MAPHEAD.* / MAPTEMP.*`) and trying to load the game with another one.
Do you specify a path to modified map set (`--mod_dir`) every time you launch the game?

**Comment by lemonsplash** [comment]
Yeah, I have a shortcut for that. I was playing the BSE90 map pack. Could have been some mixup on my site, but not really sure how that could have happened. Everything seems fine now, but I'll keep an eye on it. Thanks for your help though and great work. Blake Stone was so underrated. Have a nice day :)
