### ISSUE TITLE
"Portable" running on Windows

### ISSUE THREAD

**Issue by mgtroyas** [bibendovsky/bstone#358]
Hello,

First of all thank you very much for your work, it's great having an option to play these games with all the modern-day advantages we are used to.

I suggest allowing a "portable" running option, so the configuration files are written in the same folther than the executable, instead of the %APPDATA% path on the Windows user profile. It coud be enabled via an internal option, or simply placing a file (i.e. "portable.ini" as PCSX2 emulator allows) on the executable folder, so it's aware of it.

**Comment by bibendovsky** [comment]
Hello,

There is a command-line option to specify path to the profile `--profile_dir`.
Run with `--profile_dir .` to use a working directory as profile.

If it's still not enough I will add such ability by placing the special file along with executable.

**Comment by mgtroyas** [comment]
Thank you, I didn't find it on the documentation, my fault.

It's enough for me using --data_dir and --profile_dir as parameters.
