### ISSUE TITLE
Windows 7 = unusable + system freeze

### ISSUE THREAD

**Issue by quetzalsly** [bibendovsky/bstone#369]
Launching precompiled exe with the data from anniversary edition 3d realms aog results in windows 7 going haywire. The system switches from aero mode to non aero mode rapidly and results in system freeze for 10 seconds at a time, I was just about able to press the restart button and not do anything else.

**Comment by bibendovsky** [comment]
@quetzalsly Does the [latest release](https://github.com/bibendovsky/bstone/releases/tag/v1.2.12) still suffers from the issue?

**Comment by bibendovsky** [comment]
Closing for now.
Fell free to reopen the issue if the problem is persisted.
You could find the latest binaries on this moment in #491.
