### ISSUE TITLE
The red card can only unlock the following floor

### ISSUE THREAD

**Issue by Irv1n3** [bibendovsky/bstone#37]
Repro steps:

1. Clean the 4th floor (for example) of a mission
2. Once in the elevator, don't go to the 5th floor but go back to the first one
3. Once on the first floor, try to go directly to the 5th floor
4. Note that you can't proceed to the selected level, the game says "Floor 5 is locked"
5. Go to the 4th floor again
6. Select the 5th floor
7. The level is now unlocked

Reproducibility: always
Severity: minor

**Comment by bibendovsky** [comment]
Fixed. Thanks for info!
