### ISSUE TITLE
Nuked OPL3 emulator

### ISSUE THREAD

**Issue by KainXVIII** [bibendovsky/bstone#372]
Does this port support Nuked https://github.com/nukeykt/Nuked-OPL3 ? And if its not - maybe there are plans to implement it?

**Comment by bibendovsky** [comment]
No, it does not. But I can try to add it later.

**Comment by KainXVIII** [comment]
> No, it does not. But I can try to add it later.

Would be great!

**Comment by bibendovsky** [comment]
Done (#374).
