### ISSUE TITLE
Impossible to complete E2M6 at 100% in Veteran skill

### ISSUE THREAD

**Issue by Irv1n3** [bibendovsky/bstone#38]
On the 6th floor of the Mission 2, I have cleaned the whole level and the last 4 remaining "enemies" can be seeing on the screen: 

![2015-12-13_00001](https://cloud.githubusercontent.com/assets/4195078/11768390/f3a98164-a1cb-11e5-9a06-3bb6f140e972.jpg)

The problem is that the Bio-tec is friendly, so I can't have 100% kill and 100% informant alive in the same time. I don't know if the friendly tag is random or set by the map but I think this particular guy should be hostile or mobile so the player can clean the level without killing him.

It's in this room:

![m2_l6](https://cloud.githubusercontent.com/assets/4195078/11768389/f3a50864-a1cb-11e5-8ca9-0d8bef935bd5.png)

**Comment by bibendovsky** [comment]
I can't reproduce the issue. Do you have saved game?

**Comment by Irv1n3** [comment]
Hey, sorry for the delay, where can I find the saves?

**Comment by bibendovsky** [comment]
On Windows they located at "C:\Users\<user name>\AppData\Roaming\bibendovsky\bstone\".
Look for file that begins with "bstone_aog_full_saved_game".
For example, file "bstone_aog_full_saved_game_0" is AOG saved game for a first slot.

**Comment by Irv1n3** [comment]
Thanks, here we go:

[bstone_aog_full_saved_game_1.zip](https://github.com/bibendovsky/bstone/files/211554/bstone_aog_full_saved_game_1.zip)

**Comment by bibendovsky** [comment]
Indeed, you need a bit of luck to complete the floor with 100% stats, because friendly tag assigned randomly.

**Comment by Irv1n3** [comment]
Do you know if the friendly tags are given when you start the whole mission or when first entering the floor?

Time to start again the mission I suppose^^

**Comment by bibendovsky** [comment]
On first visit of the floor.
