### ISSUE TITLE
Change description of "is windowed" for windowed fullscreen.

### ISSUE THREAD

**Issue by adelpha** [bibendovsky/bstone#383]
I thought that alt-tabbing out of the game was broken until I realised that I could set windowed fullscreen mode by just setting the windowed resolution to the full res of my primary monitor.

It might be better to instead have a switch named "Exclusive Fullscreen" that has the opposite state to the "Is windowed" switch, to make it clear that in "Fullscreen" mode you can't alt-tab out, and maybe even another switch called "Windowed Fullscreen" that automatically sets the window to the current desktop resolution of the primary monitor.

I imagine most users appreciate the ability to tab out of the game when necessary, and that exclusive fullscreen mode will have very few users. Even with 2 monitors, in fullscreen mode you can't tab to the other monitor because the game grabs mouse focus back after a few seconds.

The behaviour is the same in all renderers.

bstone v1.2.11
Windows 10 Pro x64 19043.1110
Intel Core i7-5820K CPU @ 3.30GHz
NVIDIA GeForce GTX 980

**Comment by bibendovsky** [comment]
I'm thinking about to ditch the fullscreen (exclusive) mode.

**Comment by bibendovsky** [comment]
Fixed (#385).
