### ISSUE TITLE
Secret wall not opening in AoG Mission 4

### ISSUE THREAD

**Issue by adelpha** [bibendovsky/bstone#384]
I don't know if this is a bug in the port or in the original game, but the northern pushwall that should open up the secret area leading to the secret level didn't open correctly. It only moved 1 unit and stopped, meaning the secret area was inaccessible. It could not be reactivated to move to its correct final position.

I'm guessing that maybe the informant in there was standing in front of where the wall was supposed to go and prevented it from moving fully? Is this expected behaviour or should the wall continue to move regardless of actors blocking it?

![bstone_aog_sshot_20210814_145815_543](https://user-images.githubusercontent.com/13021896/129448809-f15af106-2842-4c98-a730-b3492367cdaf.png)
![bstone_aog_sshot_20210814_145819_623](https://user-images.githubusercontent.com/13021896/129448812-a64d18dc-eaa3-46ee-bd51-10233735fb39.png)

**Comment by bibendovsky** [comment]
> I'm guessing that maybe the informant in there was standing in front of where the wall was supposed to go and prevented it from moving fully?

The informant is a *wandering* one. But his initial position does not block the pushwall.

> Is this expected behaviour or should the wall continue to move regardless of actors blocking it?

Moving pushwall stops when it's 1) moved two tiles or 2) blocked by an object (decoration, enemy, etc.).

--------

Probably it's design error.
On the same level there is another secret area with two pushwalls and enemies inside.
And those pushwalls protected by special map plane tile ("Guard Block").

**Comment by adelpha** [comment]
Fair enough, map design bug. Closing this. Thanks for clearing it up!
