### ISSUE TITLE
Segfault when selecting OpenAL on Linux

### ISSUE THREAD

**Issue by mrmatteastwood** [bibendovsky/bstone#386]
**Steps to Reproduce:**
1. Compile bstone on Linux
2. Run bstone from terminal (./bstone)
3. In main menu, navigate to sound options
4. Select OpenAL driver
5. Confirm

**Expected Results:**
The game should recognize the system-wide installed OpenAL driver and produce 3D audio.

**Current Results:**
The game segfaults with the following error message displayed in the terminal:

[SND] Initializing audio
[SND] ------------------
[SND_OAL] Default library: "libopenal.so"
[SND_OAL] Library: ""
[SND_OAL] Device name: ""
ERROR: [SND] Failed to initialize mixer.
Segmentation fault (core dumped)

**Notes:**
- I compiled bstone in an Xubuntu VM, then moved the resulting _install_ folder to my host machine (Linux Mint 20.2).
- I also grabbed libopenal.so.1.19.1 from /lib/x86_64-linux-gnu and moved it to the install folder, where the executable resides, renaming it to libopenal.so. That didn't make a difference.
- My system specs: https://termbin.com/t2eyy

**Comment by bibendovsky** [comment]
Fixed (#388).
