### ISSUE TITLE
Play 'use' sound only when touching a wall

### ISSUE THREAD

**Issue by bibendovsky** [bibendovsky/bstone#39]
Original games plays 'hit wall' sound when holding 'use' key without checking what we interacting with.

**Comment by bibendovsky** [comment]
8bd1b85210e179e3c68b6798dd97b5ee500a5f37
Play sound only when interacting with wall or push-wall.

**Comment by Irv1n3** [comment]
Actually this is not totally my issue here, but more the little noise at the end of a 'use' action that I found annoying (you can hear this clearly on the video).

It's probably part of the sound played and not related to the code, so there's nothing you can do I assume^^

**Comment by bibendovsky** [comment]
It's not just at the end of a 'use' action, it's playing while you holding the 'use' action. In Wolfenstein 3D you should also hear such noise while you holding a 'use' action and do not interacting with door or push-wall. In Blake Stone developers decided to play a 'hit wall' sound always while you holding the 'use' action.
