### ISSUE TITLE
Inventory not reset on death

### ISSUE THREAD

**Issue by jwaffe75** [bibendovsky/bstone#395]
In the DOS game, if you were killed on a floor, you were sent back to the elevator on that floor with just the auto charge pistol.

I think this made the game more fun because once you have all 5 weapons and a pile of ammo, there's not really all that much to find in the secrets.

As a hack, I tried enabling this block, with `#if 1` instead and it seemed to work fine in Aliens of Gold so far.

https://github.com/bibendovsky/bstone/blob/48333f634bb9db1c5e8ce1f110295f499c1faaa1/src/3d_game.cpp#L3126-L3134

Since this code was disabled I'm assuming there was something wrong with it, but it would be nice to have this feature back.

**Comment by timodoherty** [comment]
I have version 2.1R and in AoG it does not return you to autocharge.  It resets your score and stats back to when I first came to the level.  I can make a video showing what I see if you want?

**Comment by bibendovsky** [comment]
Reverted experiment #396 back since the original game restores the state as it was at the (re)visit of a floor.
