### ISSUE TITLE
Latest Commit:  "identifier not found"

### ISSUE THREAD

**Issue by sudobbq** [bibendovsky/bstone#399]
Hey, Boris:  I hope you're okay over there.  Many blessings to you and your family.  Please lookout after yourself.

For anyone else playing with the code in the meantime, have you gotten the latest commit to build?  I'm getting this error in VS

```
Error	C3861	'SDL_CreateRGBSurfaceWithFormat': identifier not found	
C:\Users\user\Source\Repos\bstone\out\build\x64-Debug\bstone	
C:\Users\user\source\repos\bstone\src\id_ca.cpp	2260	
```

**Comment by bibendovsky** [comment]
This function is from SDL v2.0.5 which obviously is not available in the previous versions.
Fixed (#411, #412).
