### ISSUE TITLE
No install target in Linux?

### ISSUE THREAD

**Issue by dubhater** [bibendovsky/bstone#40]
I ran the following commands:
```
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr ..
	make
```
which worked fine. But ``make install`` says "make: *** No rule to make target 'install'.  Stop."

My system is Arch Linux.

**Comment by bibendovsky** [comment]
Indeed, I missed this step completely. I'll add installation rule for next release. Thanks for info!

**Comment by bibendovsky** [comment]
Added in develop branch (53027beb92d8620a5e219fb8104b418e0009fa7e).
