### ISSUE TITLE
One-way doors always shown as locked (red lights)

### ISSUE THREAD

**Issue by ljacqu** [bibendovsky/bstone#404]
Big fan of this project!

I noticed two discrepancies to the original, namely one-way doors always have red lights in the source port, whereas the original shows green lights on doors that aren't locked, and only doors that require a key card have red lights.

Additionally, the ammo packs are reversed: they have red points at the bottom when the pack is full and green points at the bottom when the pack is unused. I'm just mentioning the ammo pack thing for completeness and don't really think it's relevant.

**Comment by bibendovsky** [comment]
Fixed (#405, #406).

Addendum
- One-way door issue applicable to accelereated renderer.
- Charge pack issue applicable to AOG.

Notes
- Loaded game will render charge pack textures as reversed until next _unexplored_ floor.

**Comment by ljacqu** [comment]
Awesome, thanks for the fixes!
