### ISSUE TITLE
Plasma Spheres have their flinching frame as part of their standard animation

### ISSUE THREAD

**Issue by ZeuxWarrior** [bibendovsky/bstone#409]
![bstone_aog_sshot_20220524_194223_032](https://user-images.githubusercontent.com/41269193/170160621-41956556-1dbb-4fcd-828f-4fd6e7efdf93.png)

I just compared this with the original AoG E4L1, and I only saw this frame whenever I shot a Plasma Sphere and randomly did no damage. Currently, though, this appears regularly in bstone while they are just flying around.

**Comment by bibendovsky** [comment]
Fixed (#410).
