### ISSUE TITLE
Compiling on Debian

### ISSUE THREAD

**Issue by aknight2015** [bibendovsky/bstone#420]
Active directory when running cmake is /home/aknight2015/Games/bstone-1.2.11/build/

When I try to compile by copying and pasting: cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/bstone-1.2.11/build/install

I get this error:
CMake Error: The source directory "/home/aknight2015/Games" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

So, I edited the cmake command to: cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/bstone-1.2.11/build/install

I get this:
-- [bstone] v1.2.11
-- [SDL2W] Version: 1.0.4
-- [SDL2W] No components were selected.
-- [SDL2W] Libraries:
CMake Error at cmake/FindSDL2W.cmake:253 (message):
  [SDL2W] Unsupported configuration.
Call Stack (most recent call first):
  src/CMakeLists.txt:62 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/aknight2015/Games/bstone-1.2.11/build/CMakeFiles/CMakeOutput.log".
[CMakeOutput.log](https://github.com/bibendovsky/bstone/files/8941269/CMakeOutput.log)

**Comment by bibendovsky** [comment]
Do you have installed SDL2 development package?

**Comment by bibendovsky** [comment]
> When I try to compile by copying and pasting: cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/bstone-1.2.11/build/instal

Fixed the instruction in 68b4193d7c90d817d8282080841c6540ba8623e6.

**Comment by aknight2015** [comment]
That solved it. Worked like a charm. Even ran without an issue.
