### ISSUE TITLE
Large volume fluctuations in SFX - some are really loud, others very silent

### ISSUE THREAD

**Issue by mrmatteastwood** [bibendovsky/bstone#424]
**Steps to Reproduce:**
1. Run bstone 1.2.11 with Aliens of Gold
2. Play

**Current Results:**
Some sounds are really loud, e.g. when pushing a wall, trying to open a locked door or dying. Others are silent, like closing doors or attacking enemies.

**Expected Results:**
Sounds should be similar in volume.

**Video:**
https://www.youtube.com/watch?v=_4vco3S7B5I
- Start at around 1:24 when the guy starts attacking. His shots are barely audible, but the wall pushing sound is very loud.
- Starting at around 1:42, listen to the guy shooting at me vs. me trying to open the locked door.
- At 1:50, the sound of the door closing is barely audible.
- At 2:20, compare the volume of the guy yelling vs. the death sound that follows

**Notes:**
- I'm running the game on Linux Mint 21 using Wine.
- It seems like the Adlib sounds are generally much louder than the digitized SFX, though that's not always the case
- It seems like sounds fade very quickly when one is further away from their emitter (e.g. enemies get silent really quickly when moving further away)
- I play in 7.1 surround and I have OpenAL32.dll from openal-soft.org in the game's root directory
- This also happens when running the game without an OpenAL32.dll in the game's root
- The video was recorded with the dev build from June 5th, but this also happens on the release version (1.2.11)

**Comment by bibendovsky** [comment]
Added #425 with builds to test.
Applies linear distance clamped model to all audio backends.

**Comment by mrmatteastwood** [comment]
@bibendovsky Checked again on my desktop using 7.1 sound and my home theatre system. I do think the volume fluctuations have dramatically improved, though the digitized (Sound Blaster) SFX still seem softer than some Adlib effects, e.g. when pushing a wall, trying to open a locked door or dying.

Also, it feels a bit like the sounds fade fast over short distances, i.e., they become fairly quiet even when the emitter (an enemy for example) is not far away.

**Comment by bibendovsky** [comment]
> I do think the volume fluctuations have dramatically improved, though the digitized (Sound Blaster) SFX still seem softer than some Adlib effects, e.g. when pushing a wall, trying to open a locked door or dying.

That is how those sound are digitized.
For example, "open door" sound uses only ~50% of amplitude range. The "close door" sound uses only ~25% of the range.

**Comment by mrmatteastwood** [comment]
@bibendovsky Ah, in that case, I think I can confirm everything works quite as it should :-)

**Comment by mrmatteastwood** [comment]
@bibendovsky Oh, hang on - unless you'd consider straying from the original intent of the game and normalizing levels a bit more? Perhaps it would make sense to amplify the sounds a tad, and perhaps make them fade more slowly as distances grow, seeing we're now using a 3D sound implementation that the original game never had? I'm thinking the game could benefit a bit from an additional "push".

**Comment by bibendovsky** [comment]
> @bibendovsky Oh, hang on - unless you'd consider straying from the original intent of the game and normalizing levels a bit more? Perhaps it would make sense to amplify the sounds a tad, and perhaps make them fade more slowly as distances grow, seeing we're now using a 3D sound implementation that the original game never had? I'm thinking the game could benefit a bit from an additional "push".

Amplification / normalization is another story. I'll add the issue to not forget about it.
Now I need to match the audio attenuation as much as possible to original.

**Comment by mrmatteastwood** [comment]
Sounds awesome. Really glad you're still working on this, it's a great source port.
