### ISSUE TITLE
AOL Crashes saving games and hitting esc?

### ISSUE THREAD

**Issue by Stingm** [bibendovsky/bstone#43]
First I want to thank you for all your work on this project. 
1. The game crashes when saving a lot.  Planet strike seems a bit more stable with this.
2. Since this new version it crashes when hitting esc after playing a bit. Example I played level 8 and got most secrets and it crashed hitting esc. I can save if I do it on start of level sometimes but once I play a bit its hit and miss.

**Comment by Stingm** [comment]
I don't know what you did but thanks. As of the last 2 versions the game is perfect so far, No more crashes. The only thing I need to check is in planetstrike there was a teleporter that when used crashed the game. I'm betting that's fixed too. Thanks for all .the hard work. You are appreciated.

**Comment by bibendovsky** [comment]
Please notify if the problem with teleporter exists or there is no problem. Thanks.

**Comment by bibendovsky** [comment]
Since there is no more problem I'm closing the issue for now.
