### ISSUE TITLE
No music on title screens and after closing automap/mission stats

### ISSUE THREAD

**Issue by mrmatteastwood** [bibendovsky/bstone#430]
**Steps to Reproduce:**
1. Launch bstone with AoG or PS
2. Observe title screen
3. Enter gameplay
4. Press Tab to bring up automap/mission stats
5. Press Tab again to close automap/mission stats

**Current results:**
No music plays on both games' title screens nor after bringing up and closing the automap during gameplay.

**Expected Results:**
Music should play.

**Notes:**
Version: wip-cb1f927bd892e0dafa8a94a790d230648c092821 from Sep 11, 2022.
Workaround: when no music plays after step 5, enter main menu and return to gameplay. Music will restart.

**Comment by bibendovsky** [comment]
Added test builds to #431.

**Comment by mrmatteastwood** [comment]
Perfect! Fix confirmed.
