### ISSUE TITLE
E3M9 - Can't open a door

### ISSUE THREAD

**Issue by Blackbird88** [bibendovsky/bstone#44]
![bstone 2016-04-09 11-32-08-42](https://cloud.githubusercontent.com/assets/4414625/14403004/b9e62fb8-fe46-11e5-9682-562196b7cfee.png)

**Comment by bibendovsky** [comment]
Do you have saved game of this issue?

**Comment by Blackbird88** [comment]
Sure
http://www72.zippyshare.com/v/8SkXsO2u/file.html

**Comment by bibendovsky** [comment]
Fixed (72a1cb22020337e3204e4baa590c05df414bbdbc).

**Comment by Blackbird88** [comment]
Works now! Thanks.
