### ISSUE TITLE
v1.2.12-1 Music faster and higher pitch than it should be 

### ISSUE THREAD

**Issue by chrisdevosnet** [bibendovsky/bstone#441]
Windows x64 running v1.2.12-1, music is immediately noticeable as faster than it should be and also at a higher pitch.

This is compared to running Blake Stone AOG full version in DosBox which is the correct speed/pitch.  Music is also fine in BStone v1.2.11 and consistent with DosBox, so the bug was introduced in v1.2.12-1.

Steps to reproduce:

- Windows x64
- Download v1.2.12-1 from the releases page (bstone_windows_x64_v1_2_12-1.zip), install with BSAOG files from GOG.com
- Run game
- Keep settings at default
- Music on Apogee intro, title screen and menu page is too fast (continues if you start a game too)
- Compare with DosBox or v1.2.11

PS Great source port, thank you for your work on this :-)

**Comment by bibendovsky** [comment]
Does this happen in both audio backends (SDL, OpenAL)?

**Comment by chrisdevosnet** [comment]
This is on the SDL backend.  I can't get OpenAL to play music with either driver, guessing I'm missing some drivers.

**Comment by bibendovsky** [comment]
Seems it's SDL v2.0.22 issue.
Here are builds compiled with SDL v2.26.0:
[bstone_windows_x64_v1_2_12-2.zip](https://github.com/bibendovsky/bstone/files/10098807/bstone_windows_x64_v1_2_12-2.zip)
[bstone_windows_x86_v1_2_12-2.zip](https://github.com/bibendovsky/bstone/files/10098808/bstone_windows_x86_v1_2_12-2.zip)
If they are OK I will update v1.2.12 release.

**Comment by chrisdevosnet** [comment]
Thank you - I've tested this with the x64 build and can confirm the music is playing the correct speed now.

**Comment by bibendovsky** [comment]
Updated [the release](https://github.com/bibendovsky/bstone/releases/tag/v1.2.12).
