### ISSUE TITLE
bstone won't record my high scores

### ISSUE THREAD

**Issue by beavinator1** [bibendovsky/bstone#443]
When I finish an episode, it just takes me back to the main menu without allowing me to add my score to the list.  Since no one else has reported this issue I assume I must be doing something wrong...any ideas?

**Comment by bibendovsky** [comment]
This may happen if your score is lower than any in the table, or you are playing in cheat mode.

**Comment by beavinator1** [comment]
Didn't realize debug mode disabled high scores, that's the answer.  Thanks!
