### ISSUE TITLE
[Windows 7] Aero disables when game run.

### ISSUE THREAD

**Issue by CortexReaver** [bibendovsky/bstone#445]
I don't know what causing it, have tried several compatibility options with no result. Well, if you do not support Windows 7 anymore, its not that critical and generally is working perfectly, most importantly capturing by OBS with no problems.

**Comment by bibendovsky** [comment]
Should be fixed in #491 (you will find the updated binaries here too).
[Latest binaries](https://github.com/bibendovsky/bstone/pull/495#issuecomment-1987374605) at this moment.

**Comment by bibendovsky** [comment]
Closing for now.
Feel free to reopen the issues if the problem still persists.
