### ISSUE TITLE
Back to demo option bug

### ISSUE THREAD

**Issue by acd2001** [bibendovsky/bstone#450]
In Windows 10 Pro 64 bit, the menu option "Back to demo"
don't works as intended.
I tested precompiled exe and last git version (eea061b).
I can't test all version (32bit, linux ecc), sorry.

**Comment by bibendovsky** [comment]
Fixed binaries:
[bstone_windows_i686_v1_2_13-wip-bf29eaf6863e234116e35335ce77da36c02ea104.zip](https://github.com/bibendovsky/bstone/files/14623944/bstone_windows_i686_v1_2_13-wip-bf29eaf6863e234116e35335ce77da36c02ea104.zip)
[bstone_windows_x86_64_v1_2_13-wip-bf29eaf6863e234116e35335ce77da36c02ea104.zip](https://github.com/bibendovsky/bstone/files/14623945/bstone_windows_x86_64_v1_2_13-wip-bf29eaf6863e234116e35335ce77da36c02ea104.zip)
