### ISSUE TITLE
Game not playable with modified maps

### ISSUE THREAD

**Issue by urbanware-org** [bibendovsky/bstone#451]
When I modify maps of the game using a map editor (e.g. MapEdit for DOS or HWE) and try to run it, the following message appears:

![mod_error](https://user-images.githubusercontent.com/19925115/226455564-f57c844a-929a-4fa5-be69-81db2a6579e2.png)

However, if I run the original game executable in DOSBox the game loads as expected and I can play the modified maps.

It would be great if this would also be possible with your source port.

**Comment by bibendovsky** [comment]
Here are the steps for [addon installation](https://github.com/bibendovsky/bstone#43---addons):
- Put addon's files into separate directory. Do not overwrite any original files!
- Run with command line option `--mod_dir` to point to this directory (i.e. `bstone.exe --mod_dir addon1`).

**Comment by urbanware-org** [comment]
Thanks for the fast reply and the information!

I misunderstood the term "add-on" in this case. I thought it was just about e.g. new graphics or something like that and did not realize that maps also are such.

Alright, thank you!

**Comment by urbanware-org** [comment]
I just tried it and it works, however, with one limitation as the `--mod_dir` command-line argument has a side-effect in my case.

Without the argument the game starts and loads the high-resolution textures located inside the `aog` sub-directory. This works fine, unless I add an `--mod_dir` argument.

I have the sub-directory `ownmaps` containing the modified files `MAPHEAD.BS6` and `MAPTEMP.BS6` so I run the game as follows:

```
bstone.exe --mod_dir ownmaps
```

When I do so, I can play my modified maps, but the high-resolution textures are not loaded. So, due to this, I have to decide whether I want to play my maps or with high-resolution textures.

**Comment by bibendovsky** [comment]
Added an issue (#452) for external textures.
I will look into it later.
As a workaround, for now, you could copy the directory with textures into addon directory.

**Comment by urbanware-org** [comment]
Thank you, that works fine! :+1:
