### ISSUE TITLE
Compilation Errors [help wanted]

### ISSUE THREAD

**Issue by AFFLiCTED1** [bibendovsky/bstone#455]
I'm a bit lost and would appreciate some help.

My end goal is to compile this and transfer it over to Batocera Linux, but since Batocera is not designed to have a build environment, compilation has to be done on a different OS and then transferred over. I've done this successfully with a few ports already (Yamagi Quake II, Doom64EX-Plus, Mario64EX, etc.) ...All that to say, I'm trying to compile this using Ubuntu 20.04 in a VirtualBox VM since it has an older `glibc` version which is compatible with Batocera v36. I've asked over on the Batocera Discord server and they couldn't offer much advice. I'd ask the "BStone" community, but there doesn't seem to be one, as far as I can see? Anyway, I figured I'd try here...

As far as I understand, I have all the dependencies installed... Which is just  GCC or Clang and `libsdl2-dev`.  I'll outline the steps so you can see where I went wrong... I'm just trying to follow what's included in the `README.md` file.

    $ git clone https://github.com/bibendovsky/bstone
    $ cd bstone
    $ mkdir install
    $ cd install
    $ cmake -D BSTONE_USE_STATIC_LINKING=ON -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=~/bstone/build/install  ..
    $ cmake --build . --target install

It compiles for a little bit and then it I get this error: [https://pastebin.com/raw/0S9zpKpp](https://pastebin.com/raw/0S9zpKpp)

I figured, ok, must just be some wip code error. No problem, I'll download a stable release. Which I did, `v1.2.12-2` . But now when I try to compile the stable release, I get this error: [https://pastebin.com/raw/0E1Nzthz](https://pastebin.com/raw/0E1Nzthz)

Again, any help is appreciated!

**Comment by AFFLiCTED1** [comment]
Thanks for the quick response! I'm not a dev and don't know jack about git, so I had to look up a guide on how to merge a pull request... I assume I did this right? 
```
ubuntu@2004:~/bstone$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	install/

nothing added to commit but untracked files present (use "git add" to track)
ubuntu@2004:~/bstone$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
ubuntu@2004:~/bstone$ get fetch origin fix/455_sdl_keycode

Command 'get' not found, but there are 18 similar ones.

ubuntu@2004:~/bstone$ git fetch origin fix/455_sdl_keycode
From https://github.com/bibendovsky/bstone
 * branch            fix/455_sdl_keycode -> FETCH_HEAD
ubuntu@2004:~/bstone$ git checkout fix/455_sdl_keycode
Branch 'fix/455_sdl_keycode' set up to track remote branch 'fix/455_sdl_keycode' from 'origin'.
Switched to a new branch 'fix/455_sdl_keycode'
ubuntu@2004:~/bstone$ cd install
ubuntu@2004:~/bstone/install$ cmake --build . --target install
Scanning dependencies of target bstone
[  0%] Building CXX object src/CMakeFiles/bstone.dir/bstone_sys_sdl_event_mgr.cpp.o
[  1%] Building CXX object src/CMakeFiles/bstone.dir/bstone_sys_sdl_exception.cpp.o
[  2%] Building CXX object src/CMakeFiles/bstone.dir/bstone_sys_sdl_gl_context.cpp.o
[  2%] Building CXX object src/CMakeFiles/bstone.dir/bstone_sys_sdl_gl_mgr.cpp.o
[  3%] Building CXX object src/CMakeFiles/bstone.dir/bstone_sys_sdl_message_box.cpp.o
[  3%] Building CXX object src/CMakeFiles/bstone.dir/bstone_sys_sdl_mouse_mgr.cpp.o
[  4%] Building CXX object src/CMakeFiles/bstone.dir/bstone_sys_sdl_renderer.cpp.o
[  4%] Building CXX object src/CMakeFiles/bstone.dir/bstone_sys_sdl_system_mgr.cpp.o
[  5%] Building CXX object src/CMakeFiles/bstone.dir/bstone_sys_sdl_texture.cpp.o
[  5%] Building CXX object src/CMakeFiles/bstone.dir/bstone_sys_sdl_texture_lock.cpp.o
[  6%] Building CXX object src/CMakeFiles/bstone.dir/bstone_sys_sdl_video_mgr.cpp.o
[  6%] Building CXX object src/CMakeFiles/bstone.dir/bstone_sys_sdl_window.cpp.o
[  7%] Building CXX object src/CMakeFiles/bstone.dir/bstone_sys_sdl_window_mgr.cpp.o
[  8%] Linking CXX executable bstone
[100%] Built target bstone
Install the project...
-- Install configuration: "Release"
-- Installing: /home/ubuntu/bstone/build/install/./bstone
-- Installing: /home/ubuntu/bstone/build/install/./bstone_changelog.txt
-- Installing: /home/ubuntu/bstone/build/install/./bstone_readme.txt
-- Installing: /home/ubuntu/bstone/build/install/./bstone_license.txt

```
It seems I was able to compile the software successfully and now and the game executes! Thank you!

**Comment by bibendovsky** [comment]
> Thanks for the quick response! I'm not a dev and don't know jack about git, so I had to look up a guide on how to merge a pull request... I assume I did this right?

Yes, it's correct usage.

> It seems I was able to compile the software successfully and now and the game executes! Thank you!

Excellent!
