### ISSUE TITLE
Portable Save Data

### ISSUE THREAD

**Issue by AskaLangly** [bibendovsky/bstone#458]
Been noticing some of my favorite games, this included, dumping saves into `%APPDATA%`, which is a nuisance if I ever have to reinstall an OS.

I'd like the ability to have a portable install. As I lack experience in PR know-how, here's what I'd like you to do:

- Have the game's code find a `portable.txt`, of a zero byte size, in the game's root.
- If found, the game shall create a `userdata` directory in the game's root.
  - If no `portable.txt` is found, continue to create in `%APPDATA%`.

This would allow new players to immediately identify where their game saves are, as well as save the headache in grabbing the files from a former OS install.

**Comment by bibendovsky** [comment]
There is a command-line option `--profile_dir` (for details see [chapter 6](https://github.com/bibendovsky/bstone/blob/master/README.md#6---profile) of README) to override the location of saved games, configuration, etc.
If it's still not enough I could add the functionality you described.
