### ISSUE TITLE
v1.1.7 compilation failure - error: ‘uninitialized_copy_n’ is not a member of ‘std’

### ISSUE THREAD

**Issue by PaddyMac** [bibendovsky/bstone#46]
[ 49%] Building CXX object CMakeFiles/bstone.dir/bstone_memory_binary_reader.cpp.o
/home/patrick/work/bstone-1.1.7/bstone_memory_binary_reader.cpp: In member function ‘bool bstone::MemoryBinaryReader::read(void*, int)’:
/home/patrick/work/bstone-1.1.7/bstone_memory_binary_reader.cpp:173:5: error: ‘uninitialized_copy_n’ is not a member of ‘std’
     std::uninitialized_copy_n(
     ^

This is using Debian 5.4.0-4 version of gcc.

**Comment by PaddyMac** [comment]
I apologize. I tried the latest git sources, and they compiled fine. This was apparently fixed with commit 2843472473b0b9d3345f2f277c9ab49a4904515e.

**Comment by bibendovsky** [comment]
Yes, I did not yet merged latest changes into the master branch. Sorry for inconvenience.
