### ISSUE TITLE
Feature Request: AoG Automap for PS

### ISSUE THREAD

**Issue by PerdGateEnjoyer** [bibendovsky/bstone#465]
In Aliens of Gold, pressing Tab brought up the Automap, which was large and easily visible. Planet Strike shrunk the automap and moved it to the status bar, making it quite hard to read. Please add an option for an AoG-style Automap that can be brought up with the Tab key.

**Comment by bibendovsky** [comment]
Featured binaries:
[bstone_windows_x86_v1_2_13-wip-e99bf6e53204c08f7b29e169287669cfdf24eb86.zip](https://github.com/bibendovsky/bstone/files/14515497/bstone_windows_x86_v1_2_13-wip-e99bf6e53204c08f7b29e169287669cfdf24eb86.zip)
[bstone_windows_x64_v1_2_13-wip-e99bf6e53204c08f7b29e169287669cfdf24eb86.zip](https://github.com/bibendovsky/bstone/files/14515496/bstone_windows_x64_v1_2_13-wip-e99bf6e53204c08f7b29e169287669cfdf24eb86.zip)

Location of the option in the menu: GAME OPTIONS => SWITCHES2 => [PS] MAP IN STATS
