### ISSUE TITLE
Informants Die Upon Reloading a QuickSave

### ISSUE THREAD

**Issue by sudobbq** [bibendovsky/bstone#467]
Statement:  Pretty much as the title says, when I quick-load from my save, informants start dying within the first couple seconds.  The issue does not go away when relaunching the source port.

I'm on level 3 of AOG, using your latest build: "1_2_13-wip-ab48190e501ba7f9617ae6200fac07c1f375ea02".  I'm playing on the hardest difficulty.  I'm using the AOG files from retail v2.1.  Issue persists no matter what renderer I use, either full screen or windowed, as well.

Here is my save file.
[bstone_aog_full_saved_game_0.zip](https://github.com/bibendovsky/bstone/files/13933068/bstone_aog_full_saved_game_0.zip)

**Comment by jpmn4ayv** [comment]
Tried this on my PC using the save file from sudobbq's post and got the same issue.  Immediately on loading the game, it says in the status screen that I killed an informant without firing a shot.
