### ISSUE TITLE
Run Key Speeds Up Player Turn Speed

### ISSUE THREAD

**Issue by sudobbq** [bibendovsky/bstone#474]
Very simple bug I found here.
As the title states when holding down the sprint key, my mouse look sensitivity scales with the value the sprint key sends.

I found this out when testing bstone on the steam deck using the latest stable proton api.  My right joystick is sending mouse inputs to the program, bstone.exe.  When holding the stick at max output, this produces a constant mouse movement, which in turn eliminates the human error produced when manually moving an actual mouse.  This validates next-to-zero variability of the mouse inputs.

To reproduce:
Hold the right analog stick that's assigned to the mouse input either right or left and then press the sprint key on/off and observe the difference in the change of turning speed.

**Comment by sudobbq** [comment]
I did some more testing, this time in DOS box.  The sprint key behavior is exactly the same, so I guess this is original intention, however when modifying the movement to meet up with WASD standards, the mouse movement speed shouldn't increase in scale when holding the run key.  

When I tested this in DOSbox, I just held the left or the right arrow key and ran the test, and can confirm that player movement speed does increase.  The same is true with the normal mouse, as well.

I'm going to rename this bug from "Sprint Key Speeds Up Mouse Look" to "Run Key Speeds Up Player Turn Speed'

**Comment by bibendovsky** [comment]
Fixed.
[bstone_windows_x64_v1_2_13-wip-eaf4cb517a0534c3e234b0084f4fa410ed917698.zip](https://github.com/bibendovsky/bstone/files/14156759/bstone_windows_x64_v1_2_13-wip-eaf4cb517a0534c3e234b0084f4fa410ed917698.zip)
[bstone_windows_x86_v1_2_13-wip-eaf4cb517a0534c3e234b0084f4fa410ed917698.zip](https://github.com/bibendovsky/bstone/files/14156760/bstone_windows_x86_v1_2_13-wip-eaf4cb517a0534c3e234b0084f4fa410ed917698.zip)
