### ISSUE TITLE
Mission 5 Floor 9 Boss - No Walking Sounds

### ISSUE THREAD

**Issue by rnveach** [bibendovsky/bstone#478]
I verified DOSBOX from GOG's boss has walking sounds. Noticed when looking into a different difference between DOS and this source. Cheating to Floor 9 in DOSBOX, I hear boss walking.

DOS: https://youtu.be/C48DZ1W1PdQ?t=3609 (not my video but it is the same as DOSBOX from GOG)
Source 1.2.12: https://www.youtube.com/watch?v=PQqIPAgl81Y

**Comment by bibendovsky** [comment]
Fixed binaries:
[bstone_windows_x86_v1_2_13-wip-7a6425753d963de946750c09af76a080c4ac9c13.zip](https://github.com/bibendovsky/bstone/files/14396378/bstone_windows_x86_v1_2_13-wip-7a6425753d963de946750c09af76a080c4ac9c13.zip)
[bstone_windows_x64_v1_2_13-wip-7a6425753d963de946750c09af76a080c4ac9c13.zip](https://github.com/bibendovsky/bstone/files/14396379/bstone_windows_x64_v1_2_13-wip-7a6425753d963de946750c09af76a080c4ac9c13.zip)
