### ISSUE TITLE
EXE Icon

### ISSUE THREAD

**Issue by rnveach** [bibendovsky/bstone#48]
It would be great if the EXE had some icon to make it more apparent that it is the one to run when its sitting in with the rest of the Blake Stone files.

**Comment by bibendovsky** [comment]
I'll add an icon for Windows builds in the next release. Thanks for suggestion!

**Comment by bibendovsky** [comment]
Added to develop branch (2165c731c46159e29dc56621338e89cc28b08551).

**Comment by bibendovsky** [comment]
Available in v1.1.8.
