### ISSUE TITLE
Small See Through Door Glitch

### ISSUE THREAD

**Issue by rnveach** [bibendovsky/bstone#485]
When playing Mission 4, Floor 1, I noticed that in certain positions you can see through the side of the doors like there is a gap in the frame. Video and pictures below.

I originally saw the issue when playing 1.2.12 but I confirmed it exists in f6f4ee21394ea26cae2368de64a5a1eec81d2728 too.

It looks like this may only occur when there is a long hallway with a door on the end. It is easier to see the glitch when there is an enemy or electric bars behind said door, which is the case in this floor. This mission/floor may be the easiest to see this, since the door from the previous room lines up with the door at the end of the hallway and this seems to be around the perfect alignment.

I tried to reproduce this on dosbox and couldn't do it. I assume dosbox is either too low resolution or it doesn't have this issue. My resolution is 1920x1080.

Video: https://youtu.be/qAjvks--8Ic
Still Image (blown up and circled):
![still](https://github.com/bibendovsky/bstone/assets/5427943/70df633b-2f25-4e4c-926d-1dda2e340a7d)

**Comment by bibendovsky** [comment]
Fixed binaries:
[bstone_windows_i686_v1_2_13-wip+ffc0f0df84c63f75c3f36baa32f13f63a8e6a4e7.zip](https://github.com/bibendovsky/bstone/files/14625058/bstone_windows_i686_v1_2_13-wip%2Bffc0f0df84c63f75c3f36baa32f13f63a8e6a4e7.zip)
[bstone_windows_x86_64_v1_2_13-wip+ffc0f0df84c63f75c3f36baa32f13f63a8e6a4e7.zip](https://github.com/bibendovsky/bstone/files/14625059/bstone_windows_x86_64_v1_2_13-wip%2Bffc0f0df84c63f75c3f36baa32f13f63a8e6a4e7.zip)

**Comment by rnveach** [comment]
@bibendovsky I checked this out and it looks like it is fixed.
