### ISSUE TITLE
Compile error in d3_dr2.cpp

### ISSUE THREAD

**Issue by miwasp** [bibendovsky/bstone#500]
Branch master compiles fine up to (and including) commit a3103131ae8f9f284fa0f62d4ed3ef642125273f. Beginning with the next commit d95b32cd3778fa7d11e647aa5cfc23531434702d i get compile errors. Error log is:

> /home/xxx/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/bstone-d95b32cd3778fa7d11e647aa5cfc23531434702d/src/d3_dr2.cpp: In function 'void AsmRefresh()':
/home/xxx/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/bstone-d95b32cd3778fa7d11e647aa5cfc23531434702d/src/d3_dr2.cpp:325:1: error: jump to label 'horizentry'
  325 | horizentry:
      | ^~~~~~~~~~
/home/xxx/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/bstone-d95b32cd3778fa7d11e647aa5cfc23531434702d/src/d3_dr2.cpp:187:22: note:   from here
  187 |                 goto horizentry;
      |                      ^~~~~~~~~~
/home/xxx/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/bstone-d95b32cd3778fa7d11e647aa5cfc23531434702d/src/d3_dr2.cpp:305:20: note:   crosses initialization of 'const double yint_1'
  305 |         const auto yint_1 = get_fractional(yintercept) + get_fractional(ystep);
      |                    ^~~~~~
/home/xxx/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/bstone-d95b32cd3778fa7d11e647aa5cfc23531434702d/src/d3_dr2.cpp:455:1: error: jump to label 'nextpix'
  455 | nextpix:
      | ^~~~~~~
/home/xxx/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/bstone-d95b32cd3778fa7d11e647aa5cfc23531434702d/src/d3_dr2.cpp:360:46: note:   from here
  360 |                                         goto nextpix;
      |                                              ^~~~~~~
/home/xxx/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/bstone-d95b32cd3778fa7d11e647aa5cfc23531434702d/src/d3_dr2.cpp:442:20: note:   crosses initialization of 'const double xint_2'
  442 |         const auto xint_2 = get_fractional(xintercept) + get_fractional(xstep);
      |                    ^~~~~~
/home/xxx/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/bstone-d95b32cd3778fa7d11e647aa5cfc23531434702d/src/d3_dr2.cpp:455:1: error: jump to label 'nextpix'
  455 | nextpix:
      | ^~~~~~~
/home/xxx/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/bstone-d95b32cd3778fa7d11e647aa5cfc23531434702d/src/d3_dr2.cpp:224:46: note:   from here
  224 |                                         goto nextpix;
      |                                              ^~~~~~~
/home/xxx/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/bstone-d95b32cd3778fa7d11e647aa5cfc23531434702d/src/d3_dr2.cpp:442:20: note:   crosses initialization of 'const double xint_2'
  442 |         const auto xint_2 = get_fractional(xintercept) + get_fractional(xstep);
      |                    ^~~~~~
/home/xxx/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/bstone-d95b32cd3778fa7d11e647aa5cfc23531434702d/src/d3_dr2.cpp:305:20: note:   crosses initialization of 'const double yint_1'
  305 |         const auto yint_1 = get_fractional(yintercept) + get_fractional(ystep);
      |                    ^~~~~~

**Comment by bibendovsky** [comment]
Fixed in 80be4602cd5f765e22dce1909495b3725d5675d3.

**Comment by miwasp** [comment]
Confirmed to work. Thank you very much.
