### ISSUE TITLE
Just a warning about the base game files

### ISSUE THREAD

**Issue by SilentMRG** [bibendovsky/bstone#506]
Greetings!

In the list "SHA-1 for AOG SW v3.0" the file "SVSWAP.BS6" is missing, without it the source port will not start. I haven't looked at the lists above, but I think the same file is also missing. I think other people didn't see it because they use BStone with the installed version of GOG or Steam, and in my case I did a "portable installation" moving the files in the list to the source port folder.

Best regards!

**Comment by bibendovsky** [comment]
No, required file is VSWAP.BS1 / VSWAP.BS6.
Also, official shareware version (v3.0) does not have such a file.
The purpose of SVSWAP is unknown to me (overlooked file?).

**Comment by SilentMRG** [comment]
Sir, I apologize for my mistake, I was referring to the "SHA-1 for AOG v3.0" list, not the one mentioned in the previous post. Anyway, in this list the file "SVSWAP.BS6" is missing. People didn't notice this because they usually copy the binary into their installed versions of GOG, Steam or ZOOM Platform. I also don't know what the "SVSWAP.BS6" file does, but it is a file whose size is 2.74 MB (2,878,696 bytes). Strangely enough, I now booted the source port without it and everything worked fine, no errors apparently.

**Comment by bibendovsky** [comment]
The section in the README named as "Required assets".
SVSWAP not required by the source port, and the original game (registered or shareware) as well.
That is why it's not included in any list.
