### ISSUE TITLE
Secret Area #4 impossible to beat 100%?

### ISSUE THREAD

**Issue by KUBA18i** [bibendovsky/bstone#52]
![](http://puu.sh/r1490/97f7e783f5.png)

I have tried to beat the map multiple times, and yet I still could not open a door which contained the last bunch of enemies(visible on map). I don't whether it's the fault of the source port, or there is some other way to open it that I don't know of. I really want to beat the game 100%, so this is bothering me.

**Comment by bibendovsky** [comment]
Walk over the tiles at [19;26], [19;27] or [19;28] to open the door for a short period of time.
You can see those three tiles as magenta vertical bar on provided image below.

![bsps_secret4_tricky_door_001](https://cloud.githubusercontent.com/assets/1597301/18274534/7f2124fc-744b-11e6-85d6-fe5c8f7cb5f8.png)

**Comment by KUBA18i** [comment]
Thank you! This particular switch was kind of hard to discover on my own. Now I have completed my perfectionist [playthrough](http://steamcommunity.com/sharedfiles/filedetails/?id=759108482).
