### ISSUE TITLE
fail on save/load planet strike

### ISSUE THREAD

**Issue by Mad-Soft** [bibendovsky/bstone#54]
When i save the game, all seems ok, but when i load this savegame fails and shows this message in terminal
ERROR: LOAD: Failed to decompress LVXX data.
In game says this savegame is on unsupported game.....
This error is random, sometimes save and load well, but others fails...

**Comment by bibendovsky** [comment]
Could you share the problematic saved game file?
Also please provide information about version of the source port (release or develop commit) do you use and on which platform (OS, x86, x64, etc.).

**Comment by Mad-Soft** [comment]
Yes i download https://github.com/bibendovsky/bstone/archive/develop.zip and compile on openSUSE Leap 42.1 x64
This is a savegame https://www.dropbox.com/s/wnvid43gtr3i44c/bstone_ps_saved_game_0?dl=0

**Comment by anorman728** [comment]
I'm actually having the same problem, but in Aliens of Gold (GOG version, if that makes any difference).  It looks like it happens after entering or exiting certain levels, for example after leaving the secret level in mission 2 (which can be found in a secret room in floor 6), and I had the same problem in mission one with any floors after floor 8.

Probably the easiest way to replicate it is by using the JAM code to get to floor 8 of mission one, saving, then loading that save.

FTR, I compiled 1.1.14 on Ubuntu 16.04, with cmake 3.5.1.  I can't seem to find what version of SDL I have, though.

Behavior isn't consistent, but I sometimes get the "Unsupported" message and sometimes get a segfault.  I have gotten the LVXX one mentioned above before, too.  The specific error message that I most often get in the console seems to be `*** Error in `./bstone': double free or corruption (out): 0x00000000043ef3e0 ***`.

The error just comes when loading, not when saving, but I don't know which is causing the problem.

Hope that helps.  I'd love to look into it myself, but I don't know the first thing about C++ dev.  (I really appreciate the project, btw.  Using those antiquated controls after I bought the Gog game was a huge disappointment!)

**Comment by bibendovsky** [comment]
Windows builds to test.
[bstone_bin_win32_v1_2_0_alpha_1.zip](https://github.com/bibendovsky/bstone/files/3641754/bstone_bin_win32_v1_2_0_alpha_1.zip)
[bstone_bin_win64_v1_2_0_alpha_1.zip](https://github.com/bibendovsky/bstone/files/3641755/bstone_bin_win64_v1_2_0_alpha_1.zip)

To build non-Windows release use branch "wip/#78_1.2.0-alpha.1"


> Probably the easiest way to replicate it is by using the JAM code to get to floor 8 of mission one, saving, then loading that save.

Could not reproduce with alpha version - should be fixed.


> FTR, I compiled 1.1.14 [Correction: 1.1.13] on Ubuntu 16.04, with cmake 3.5.1. I can't seem to find what version of SDL I have, though.

Run CMake again and look up it's output for "SDL2W: Found version" message.
