### ISSUE TITLE
Unable to compile on Mac OS X 10.12.5

### ISSUE THREAD

**Issue by eisnerguy1** [bibendovsky/bstone#56]
So, I'm trying to compile it on Mac OS X 10.12.5.  I've got cmake 2.8.12.2 & sdl2 2.0.5 was installed via homebrew.  It gets to this point:
```
[100%] Building CXX object CMakeFiles/bstone.dir/vgapal.cpp.o
Linking CXX executable bstone
```

And then this error message pops up:
```
ld: library not found for -lSDL2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bstone] Error 1
make[1]: *** [CMakeFiles/bstone.dir/all] Error 2
make: *** [all] Error 2
```

I'm not sure what's causing this problem.

**Comment by clobber** [comment]
>ld: library not found for -lSDL2

CMake or the build script isn't doing a good job at finding where SDL2 lives on your machine. Depending on where you have installed SDL2, you can work around this by setting paths for a few CMake variables:

`SDL_INCLUDE_DIRS = /Library/Frameworks/SDL2.framework/Headers`

`SDL_LIBRARIES = /Library/Frameworks/SDL2.framework/SDL2;-framework Cocoa`

This assumes SDL2.framework from https://www.libsdl.org/download-2.0.php is installed in /Library/Frameworks.

**Comment by bibendovsky** [comment]
@eisnerguy1 is problem solved?

**Comment by bibendovsky** [comment]
I'm closing this for now due to inactivity.
