### ISSUE TITLE
Teleporters Result In Black Viewscreen

### ISSUE THREAD

**Issue by DanKorell** [bibendovsky/bstone#74]
On playing Aliens of Gold, E6M9, the level starts with a teleporter. You enter the teleporter, the screen goes black, then the message comes up saying that you are teleporting in and the viewscreen stays black. If you then bring up the map and close it then the viewscreen does then come up allowing you to continue playing.

In fact, it looks like every teleporter has this issue, as having just finished Aliens of Gold I then started up Planet Strike, and after clearing the first level and using the teleporter to get to the second level, again when teleporting in the viewscreen remains black, but after bringing up the stats and then closing them the viewscreen is then displayed.

So, it's not a game breaking issue as the map/stats screen can be used to workaround the issue, but I don't recall this happening with the previous version, only since 1.1.8 was released.

**Comment by LordKane1701** [comment]
I can confirm this bug happens as well

**Comment by bibendovsky** [comment]
Fixed in v1.1.9.

**Comment by DanKorell** [comment]
Just tried 1.1.9 and teleporters work again now. Many thanks.
