### ISSUE TITLE
Weapon sprite drawn slightly too high

### ISSUE THREAD

**Issue by PoniestPonypony** [bibendovsky/bstone#87]
Here is a screenshot of BStone running at 1366 x 768:
![bstone_aog_1366x768](https://user-images.githubusercontent.com/12336450/34733299-95ec735e-f5b3-11e7-9723-acd883e24f1b.png)

If you zoom in, you can see that there is a gap, albeit very small (1 pixel height), between the bottom of the weapon sprite and the top of the status bar (the gap is just above the black bar).  This issue is also present in Planet Strike.

**Comment by bibendovsky** [comment]
Fixed (#98).
